package cn.pegasus.setup;
final class KpaLayout {
 private KpaLayout() {}
 static final int OVERLAY_TITLE_TEXT=27,RESULT_TEXT=20,APP_TITLE_TEXT=18,OVERLAY_PROGRESS_TEXT=18,TITLE_TEXT=16,ITEM_TEXT=15,SECTION_TEXT=14,BODY_TEXT=13,DETAIL_TEXT=12,CAPTION_TEXT=11,META_TEXT=10;
 static final int BUTTON_TEXT=13,DIALOG_BUTTON_TEXT=14;
 static final int EDGE=16,STEP_BAR=34,FOOTER=56,ACTION=40,TUTORIAL_ACTION=52;
 static final int DIALOG_HEADER=56,DIALOG_FOOTER=56,DIALOG_ACTION=44,DIALOG_BUTTON_MIN=92,TILE=30,BROWSER_ROW=54,RADIUS=8,FOCUS_STROKE=2,BORDER_STROKE=1;
}
