package cn.pegasus.setup;

import android.app.*;
import android.content.*;
import android.content.pm.*;
import android.graphics.Color;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.os.storage.*;
import android.provider.Settings;
import android.provider.DocumentsContract;
import android.provider.OpenableColumns;
import android.database.Cursor;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
 static final String ROOT_GUIDE="设备→Root 脚本：运行 KPA_Authorize.sh";
 static final long ROOT_GUIDE_MS=15000;
 final int bg=KpaTheme.BG,panel=KpaTheme.PANEL,fg=KpaTheme.TEXT,muted=KpaTheme.MUTED,accent=KpaTheme.PRIMARY,success=KpaTheme.SUCCESS;
 final int runningColor=KpaTheme.RUNNING,warningColor=KpaTheme.WARNING,errorColor=KpaTheme.ERROR,buttonSurface=KpaTheme.BUTTON,disabledSurface=KpaTheme.DISABLED,disabledBorder=KpaTheme.DISABLED_BORDER;
 final TextView[] stepTabs=new TextView[4];
 LinearLayout rootShell,footerRow,footerLeft;
 LinearLayout content; LinearLayout screen; boolean directionalSelection=false; Button primaryAction,secondaryAction; String footerNotice=""; int footerColor; TextView status,logView,selection; ScrollView scroll,logScroll;
 boolean skipGbaExpected=false; boolean authorizationObserved=false; boolean finalized=false,runningOverlayShown=false,statusPulseOn=false; String authorizationToken=""; boolean permissionPrompted=false,discoveryRunning=false,discovered=false; int progress=0,itemDone=0,itemTotal=0,statusPulseColor=0; double preciseProgress=0; String progressPhase="",currentWork=""; TextView progressText; ProgressBar progressBar; final Handler monitor=new Handler(Looper.getMainLooper());
 final Runnable statusPulse=new Runnable(){public void run(){if(step!=2||primaryAction==null||primaryAction.isEnabled())return;statusPulseOn=!statusPulseOn;GradientDrawable state=shape(statusPulseOn?statusPulseColor:buttonSurface);state.setStroke(dp(1),statusPulseColor);primaryAction.setBackground(state);primaryAction.setTextColor(statusPulseOn?bg:statusPulseColor);monitor.postDelayed(this,700);}};
 File config,gba,destination=new File(SetupEngine.HOME); AppSpec[] apps=AppSpec.list();
 SetupEngine engine; File run; int step=0; boolean busy=false;
 final ExecutorService executor=Executors.newSingleThreadExecutor();
 final Map<String,Boolean> manualDirectory=new HashMap<>();
 PowerManager.WakeLock wake; final Runnable heartbeat=new Runnable(){public void run(){if(!interactionLocked())return;pollRunningOverlay();monitor.postDelayed(this,2000);}};
 boolean rootPassed=false;
 boolean rootChecking=false;long lastRootCheck=0;
 final Handler rootGuideHandler=new Handler(Looper.getMainLooper()); Toast rootGuideToast; boolean rootGuideActive=false; long rootGuideUntil=0;
 final Runnable rootGuideRepeat=new Runnable(){public void run(){long left=rootGuideUntil-SystemClock.uptimeMillis();if(!rootGuideActive||left<=0){stopRootPageGuide();return;}if(rootGuideToast!=null)rootGuideToast.cancel();rootGuideToast=Toast.makeText(MainActivity.this,ROOT_GUIDE,Toast.LENGTH_LONG);rootGuideToast.show();rootGuideHandler.postDelayed(this,Math.min(3000,left));}};
 String selectionReport="",summaryReport="",spaceReport="";
 final Map<String,Boolean> verifiedPermissions=new HashMap<>();
 ImportSources sources=new ImportSources();
 final Map<String,String> initialStates=new LinkedHashMap<>();
 String pendingKind="gba";
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);markFreshInstall();restore();authorizationToken=getPreferences(0).getString("authorizationToken","");if(authorizationToken.isEmpty()){authorizationToken=UUID.randomUUID().toString();getPreferences(0).edit().putString("authorizationToken",authorizationToken).apply();}if(!authorizationPassed())step=0;render();

 }
 void autoRootCheck(boolean force){
  if(rootChecking||busy||(!force&&System.currentTimeMillis()-lastRootCheck<15000))return;
  rootChecking=true;lastRootCheck=System.currentTimeMillis();executor.execute(()->{boolean ok=false;try{new RootBridge(this).check();ok=true;}catch(Exception ignored){}final boolean passed=ok;runOnUiThread(()->{rootChecking=false;rootPassed=passed;});});
 }
 int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+0.5f);}
 boolean deviceSupported(){return "ARBOR".equalsIgnoreCase(Build.MANUFACTURER)&&"GT78-VN".equalsIgnoreCase(Build.MODEL)&&"GT78-VN".equalsIgnoreCase(Build.DEVICE);}
 String deviceIdentity(){return Build.MANUFACTURER+" · "+Build.MODEL+" · "+Build.DEVICE;}
 String authorizationNotice(){
  if(!deviceSupported())return "未知机型，谨慎使用！";
  if(!Environment.isExternalStorageManager())return "请先授予文件权限\n授权后会自动生成 KPA_Authorize.sh";
  if(!authorizationPassed())return "掌机管理 → Root 脚本 → 运行 KPA_Authorize.sh\n执行结果页面下滑到最后，出现 SUCCESS 后返回 KPA助手";
  return "授权通过，可以继续";
 }
 TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(2),0,dp(4));return t;}
 void add(String s,int size,int color){content.addView(text(s,size,color));}
 GradientDrawable shape(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(KpaLayout.RADIUS));return d;}
 GradientDrawable outlinedShape(int color,int border){GradientDrawable d=shape(color);d.setStroke(dp(KpaLayout.BORDER_STROKE),border);return d;}
 void card(String title,String subtitle,Runnable body){
  LinearLayout parent=content,c=new LinearLayout(this);c.setOrientation(1);c.setPadding(dp(16),dp(12),dp(16),dp(12));c.setBackground(shape(panel));
  LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,0,1);p.setMargins(0,dp(4),0,dp(4));parent.addView(c,p);content=c;
  if(step==3&&!title.isEmpty()){TextView heading=text(title,title.equals("KPA助手")?18:14,title.equals("KPA助手")?fg:muted);heading.setTypeface(null,Typeface.BOLD);content.addView(heading);}if(subtitle!=null&&!subtitle.isEmpty())add(subtitle,12,muted);body.run();content=parent;
 }
 void actions(String left,Runnable l,String right,Runnable r){
  LinearLayout row=new LinearLayout(this);row.setOrientation(0);content.addView(row);
  String[] names={left,right};Runnable[] a={l,r};for(int i=0;i<2;i++){Button b=new Button(this);b.setText(names[i]);b.setTextSize(KpaLayout.BUTTON_TEXT);b.setAllCaps(false);b.setTextColor(busy?muted:fg);b.setBackground(outlinedShape(buttonSurface,KpaTheme.BORDER));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(step==3?KpaLayout.TUTORIAL_ACTION:KpaLayout.ACTION),1);p.setMargins(i==0?0:dp(4),dp(8),i==0?dp(4):0,dp(4));row.addView(b,p);if(i==0)secondaryAction=b;else primaryAction=b;b.setEnabled(!busy&&(step!=0||i==0||(Environment.isExternalStorageManager()&&authorizationPassed()))&&!(step==1&&i==1&&(discoveryRunning||names[i].equals("下一步")&&!selectionReport.startsWith("✓"))));boolean checking=step==1&&i==1&&discoveryRunning;if(checking){b.setBackground(outlinedShape(KpaTheme.RUNNING_SURFACE,runningColor));b.setTextColor(runningColor);}else if(!b.isEnabled()){b.setTextColor(muted);b.setBackground(outlinedShape(disabledSurface,disabledBorder));b.setAlpha(1f);}else if(i==1&&step!=3){boolean missing=step==1&&!selectionReport.startsWith("✓");boolean passed=names[i].equals("下一步");b.setBackground(shape(missing?warningColor:passed?success:accent));b.setTextColor(missing||passed?bg:fg);}final int n=i;focusable(b);b.setOnClickListener(v->a[n].run());}
 }
 boolean warningText(String value){return value.contains("不足")||value.contains("失败")||value.contains("异常")||value.contains("冲突")||value.contains("未找到")||value.contains("多个")||value.contains("警告")||value.contains("WARNING")||value.contains("错误")||value.contains("ERROR")||value.contains("FAIL");}
 void hint(String value,int color){footerNotice=value;footerColor=warningText(value)?errorColor:value.contains("通过")||value.contains("✓")?success:value.contains("正在")||value.contains("检测中")||value.contains("执行中")?runningColor:value.contains("等待")||value.contains("待执行")||value.contains("待授权")||value.contains("请")?warningColor:color;}
 void terminal(String value){logView=text(value,KpaLayout.DETAIL_TEXT,accent);styleLog(value);logView.setTypeface(Typeface.MONOSPACE);logView.setPadding(dp(12),dp(9),dp(12),dp(9));logView.setMinHeight(0);if(step==1)logView.setMaxLines(4);logView.setBackground(shape(KpaTheme.TERMINAL));logView.setGravity(Gravity.TOP);logView.setTextIsSelectable(step!=2);if(step==2)logView.setOnClickListener(v->showLog());if(step==2){logScroll=new ScrollView(this);logScroll.setFillViewport(true);logScroll.addView(logView,new ScrollView.LayoutParams(-1,-2));content.addView(logScroll,new LinearLayout.LayoutParams(-1,0,1));scrollLog();}else content.addView(logView,new LinearLayout.LayoutParams(-1,0,1));}
 void scrollLog(){if(logScroll!=null)logScroll.post(()->logScroll.fullScroll(View.FOCUS_DOWN));}
 final java.util.Map<String,String> displayedLogTimes=new java.util.HashMap<>();
 String logTime(){return new java.text.SimpleDateFormat("HH:mm:ss",java.util.Locale.CHINA).format(new java.util.Date());}
 String chineseLog(String value){StringBuilder out=new StringBuilder();String time=logTime();boolean permissionShown=false;for(String raw:value.split("\n")){String l=raw.trim();if(l.isEmpty())continue;
  if(l.startsWith("Granted android.permission")||l.equals("All-files permission granted"))continue;
  if(l.startsWith("Storage permissions:")){if(permissionShown)continue;permissionShown=true;l="应用存储权限已设置："+l.substring(l.indexOf(':')+1).trim();}
  l=l.replaceAll("(?s)Failed to allocate.*","错误：内存不足").replace("KPA initialization started.","开始初始化").replace("Installing:","安装应用：").replace("Cleaning old data:","清理旧配置：").replace("Applying custom configuration","覆盖定制配置").replace("Applying GBA package","导入 GBA整包").replace("Applying game lists:","覆盖游戏列表：").replace("Applying Android overlay","覆盖安卓目录").replace("GBA package renamed:","GBA整包已归档：").replace("Imported ","已覆盖：").replace("APPLY_OK","文件覆盖完成").replace("Success","应用安装完成").replace("Failed, exit code","错误：执行中断，代码").replace("Temporary path conflict","错误：临时文件冲突").replace("Unsafe symlink","错误：路径不安全").replace("Unexpected application security label","错误：应用目录权限异常").replace("RetroArch base.apk extraction completed","RA 资源释放完成").replace("RetroArch base.apk extraction timed out","错误：RA 资源释放超时").replace("Unable to read RetroArch version","错误：无法读取 RA 版本").replace("SUCCESS: KPA initialization completed. Return to KPA Assistant.","初始化完成，请返回 KPA助手").replace("ERROR: KPA initialization failed. Return to KPA Assistant for details.","错误：初始化失败，请返回查看日志").replace("Completed. Return to KPA Assistant.","初始化已完成").replace("Run from the handheld Root script entry","请在掌机管理的 Root 脚本页运行");
  l=l.replace("APPLY_FILES_OK","覆盖文件检查通过").replace("FILES_OK","文件存在检查通过").replace(": OK","：通过").replace("Permission denied","错误：访问被拒绝").replace("No space left on device","错误：存储空间不足").replace("No such file or directory","错误：文件不存在").replace("Failure [","安装失败 [").replace("WARNING:","提醒：");
  if(!l.startsWith("[")){if(!displayedLogTimes.containsKey(l))displayedLogTimes.put(l,time);l="["+displayedLogTimes.get(l)+"] "+l;}out.append(l).append('\n');}return out.toString().trim();}
 int logColor(String line){if(line.contains("错误")||line.contains("失败")||line.contains("被拒绝")||line.contains("不足")||line.contains("✕"))return errorColor;if(line.contains("提醒")||line.contains("跳过")||line.contains("未选择")||line.contains("部分完成"))return warningColor;if(line.contains("开始")||line.contains("正在")||line.contains("准备")||line.contains("清理")||line.contains("安装")||line.contains("导入")||line.contains("覆盖")||line.contains("检查")||line.contains("核验中"))return runningColor;return muted;} void styleLog(String value){if(logView==null)return;value=chineseLog(value);logView.setTag(value);android.text.SpannableString styled=new android.text.SpannableString(value);int start=0;for(String line:value.split("\n",-1)){styled.setSpan(new android.text.style.ForegroundColorSpan(logColor(line)),start,start+line.length(),android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);start+=line.length()+1;}logView.setText(styled);}
 TextView dialogTitle(String value){TextView title=new TextView(this);title.setText(value);title.setTextSize(KpaLayout.TITLE_TEXT);title.setTextColor(fg);title.setIncludeFontPadding(false);title.setMinHeight(dp(56));title.setGravity(Gravity.CENTER_VERTICAL);title.setPadding(dp(28),0,dp(28),0);title.setBackgroundColor(KpaTheme.BAR);title.setSingleLine(true);title.setMinHeight(dp(56));title.setMaxHeight(dp(56));title.setMinimumHeight(dp(56));title.setEllipsize(android.text.TextUtils.TruncateAt.MIDDLE);title.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-1,dp(56)));return title;}
 ScrollView choiceView(String[] labels,android.content.DialogInterface.OnClickListener callback){LinearLayout list=new LinearLayout(this);list.setOrientation(1);list.setPadding(dp(14),dp(8),dp(14),dp(8));for(int i=0;i<labels.length;i++){final int n=i,before=list.getChildCount();optionCard(list,labels[i],"",()->{AlertDialog previous=currentDialog;changeDialog(previous,()->callback.onClick(null,n));});View item=list.getChildAt(before);item.setMinimumHeight(dp(58));if(item instanceof LinearLayout)((LinearLayout)item).setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams lp=(LinearLayout.LayoutParams)item.getLayoutParams();lp.setMargins(0,dp(4),0,dp(4));item.setLayoutParams(lp);}ScrollView scroll=new ScrollView(this);scroll.setVerticalScrollBarEnabled(false);scroll.setBackgroundColor(bg);scroll.addView(list);scroll.setTag(Integer.valueOf(labels.length));return scroll;}
 AlertDialog currentDialog;String currentDialogTitle="";
 int dialogGeneration=0;final java.util.Set<AlertDialog> fullDialogs=new java.util.HashSet<>();
 boolean fullDialog(String title){return Arrays.asList("调整选择","应用选择","覆盖资料","操作记录","初始化计划","最后授权与配置").contains(title);}
 class UniformDialogBuilder extends AlertDialog.Builder{
  String titleValue="";java.util.Map<Integer,android.content.DialogInterface.OnClickListener> clicks=new java.util.HashMap<>();UniformDialogBuilder(){super(MainActivity.this);}
  @Override public AlertDialog.Builder setTitle(CharSequence title){titleValue=title.toString();return super.setTitle(title);}
  @Override public AlertDialog.Builder setCustomTitle(View title){if(title instanceof TextView)titleValue=((TextView)title).getText().toString();return super.setCustomTitle(title);}
  @Override public AlertDialog.Builder setNegativeButton(CharSequence text,android.content.DialogInterface.OnClickListener click){clicks.put(AlertDialog.BUTTON_NEGATIVE,click);return super.setNegativeButton(text,click);}
  @Override public AlertDialog.Builder setPositiveButton(CharSequence text,android.content.DialogInterface.OnClickListener click){clicks.put(AlertDialog.BUTTON_POSITIVE,click);return super.setPositiveButton(text,click);}
  @Override public AlertDialog.Builder setNeutralButton(CharSequence text,android.content.DialogInterface.OnClickListener click){clicks.put(AlertDialog.BUTTON_NEUTRAL,click);return super.setNeutralButton(text,click);}
  void bind(AlertDialog template,AlertDialog host){currentDialogTitle=titleValue;host.setOnKeyListener((dialog,key,event)->handleDialogKey(host,titleValue,key,event));bindFocusKeys(host.getWindow().getDecorView(),host,titleValue);for(java.util.Map.Entry<Integer,android.content.DialogInterface.OnClickListener> entry:clicks.entrySet()){Button button=template.getButton(entry.getKey());if(button!=null)button.setOnClickListener(view->{int before=dialogGeneration;if(entry.getValue()!=null)entry.getValue().onClick(host,entry.getKey());if(before!=dialogGeneration&&currentDialog==host)return;closeAfterReplacement(host);});}}
  @Override public AlertDialog create(){AlertDialog d=super.create();d.getWindow().setWindowAnimations(0);
   if(fullDialog(titleValue)&&currentDialog!=null&&currentDialog.isShowing()&&fullDialogs.contains(currentDialog)){AlertDialog host=currentDialog;d.create();fillDialog(d);View root=d.getWindow().getDecorView().findViewWithTag("kpaDialog");if(root.getParent() instanceof ViewGroup)((ViewGroup)root.getParent()).removeView(root);host.setContentView(root);dialogGeneration++;bind(d,host);return host;}
   if(fullDialog(titleValue)){fullDialogs.add(d);d.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);d.getWindow().setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(bg));d.getWindow().setLayout(-1,-1);}
   d.setOnShowListener(v->{currentDialog=d;dialogGeneration++;fillDialog(d);bind(d,d);});d.setOnDismissListener(v->{fullDialogs.remove(d);if(currentDialog==d){currentDialog=null;currentDialogTitle="";}});return d;}
 }

 void closeAfterReplacement(AlertDialog previous){AlertDialog replacement=currentDialog;if(previous==null||!previous.isShowing())return;if(replacement==null||replacement==previous||!replacement.isShowing()){previous.dismiss();return;}View decor=replacement.getWindow().getDecorView();android.view.ViewTreeObserver.OnDrawListener listener=new android.view.ViewTreeObserver.OnDrawListener(){boolean done=false;public void onDraw(){if(done)return;done=true;decor.post(()->{if(decor.getViewTreeObserver().isAlive())decor.getViewTreeObserver().removeOnDrawListener(this);if(previous.isShowing())previous.dismiss();});}};decor.getViewTreeObserver().addOnDrawListener(listener);decor.invalidate();}
 void changeDialog(AlertDialog previous,Runnable next){int before=dialogGeneration;next.run();if(before!=dialogGeneration&&currentDialog==previous)return;closeAfterReplacement(previous);}

 AlertDialog.Builder dialogBuilder(){return new UniformDialogBuilder();}
 void styleDialogButton(Button button,int which){
  boolean enabled=button.isEnabled(),positive=which==AlertDialog.BUTTON_POSITIVE;
  String label=button.getText().toString();
  boolean completion=label.contains("确定")||label.contains("确认")||label.contains("完成")||label.contains("下一步");
  int fill=!enabled?disabledSurface:positive?(completion?success:accent):buttonSurface;
  int ink=!enabled?muted:positive?bg:fg;
  GradientDrawable style=shape(fill);
  style.setStroke(dp(1),!enabled?disabledBorder:positive?fill:KpaTheme.BORDER);
  button.setTextColor(ink);button.setBackground(style);button.setAlpha(1f);
 }
 boolean handleDialogKey(AlertDialog host,String titleValue,int key,KeyEvent event){
  if(event.getAction()!=KeyEvent.ACTION_DOWN)return controllerKey(key)||key==KeyEvent.KEYCODE_BACK;
  if(key==KeyEvent.KEYCODE_BACK||key==KeyEvent.KEYCODE_BUTTON_B){if(titleValue.equals("应用选择")||titleValue.equals("覆盖资料"))showSelectionOptions();else{if(titleValue.equals("调整选择"))finishSelection();host.cancel();}return true;}
  if(directionKey(key)){moveFocus(host.getWindow().getDecorView(),host.getCurrentFocus(),focusDelta(key));return true;}
  if(key==KeyEvent.KEYCODE_BUTTON_A){View focused=host.getCurrentFocus();if(focused!=null&&focused.isEnabled()&&focused.isClickable())focused.performClick();return true;}
  return false;
 }
 void bindFocusKeys(View view,AlertDialog host,String title){if(view.isFocusable())view.setOnKeyListener((v,key,event)->handleDialogKey(host,title,key,event));if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++)bindFocusKeys(group.getChildAt(i),host,title);}}
 void collectFocusables(View view,ArrayList<View> out){if(view.isShown()&&view.isEnabled()&&view.isFocusable()&&view.isClickable())out.add(view);if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++)collectFocusables(group.getChildAt(i),out);}}
 boolean inside(View root,View child){View current=child;while(current!=null){if(current==root)return true;android.view.ViewParent parent=current.getParent();current=parent instanceof View?(View)parent:null;}return false;}
 boolean directionKey(int key){return key==KeyEvent.KEYCODE_DPAD_UP||key==KeyEvent.KEYCODE_DPAD_LEFT||key==KeyEvent.KEYCODE_DPAD_DOWN||key==KeyEvent.KEYCODE_DPAD_RIGHT;}
 int focusDelta(int key){return key==KeyEvent.KEYCODE_DPAD_UP||key==KeyEvent.KEYCODE_DPAD_LEFT?-1:1;}
 void selectFocus(View view){view.requestFocusFromTouch();view.requestFocus();}
 void moveFocus(View scope,View current,int delta){directionalSelection=true;ArrayList<View> choices=new ArrayList<>();collectFocusables(scope,choices);if(choices.isEmpty())return;int at=choices.indexOf(current);if(at<0)at=delta<0?0:-1;selectFocus(choices.get((at+delta+choices.size())%choices.size()));}
 void moveScreenFocus(int key){directionalSelection=true;ArrayList<View> choices=new ArrayList<>();collectFocusables(screen,choices);choices.remove(logView);if(choices.isEmpty())return;View current=getCurrentFocus();if(!choices.contains(current)){View start=primaryAction!=null&&primaryAction.isEnabled()?primaryAction:secondaryAction!=null&&secondaryAction.isEnabled()?secondaryAction:choices.get(0);selectFocus(start);return;}android.graphics.Rect from=new android.graphics.Rect();current.getGlobalVisibleRect(from);int fx=from.centerX(),fy=from.centerY();View best=null;long bestScore=Long.MAX_VALUE;for(View candidate:choices){if(candidate==current)continue;android.graphics.Rect to=new android.graphics.Rect();candidate.getGlobalVisibleRect(to);int dx=to.centerX()-fx,dy=to.centerY()-fy;boolean vertical=key==KeyEvent.KEYCODE_DPAD_UP||key==KeyEvent.KEYCODE_DPAD_DOWN,valid=key==KeyEvent.KEYCODE_DPAD_UP?dy<0:key==KeyEvent.KEYCODE_DPAD_DOWN?dy>0:key==KeyEvent.KEYCODE_DPAD_LEFT?dx<0:dx>0;if(!valid||!vertical&&Math.abs(dy)>Math.max(from.height(),to.height())/2)continue;long score=vertical?(long)Math.abs(dy)*10000+Math.abs(dx):(long)Math.abs(dx)*10000+Math.abs(dy);if(score<bestScore){bestScore=score;best=candidate;}}if(best!=null)selectFocus(best);}
 void fillDialog(AlertDialog d){if(d.getWindow().getDecorView().findViewWithTag("kpaDialog")!=null)return;
  int customId=getResources().getIdentifier("custom","id","android");ViewGroup custom=d.findViewById(customId);View body=null;if(custom!=null&&custom.getChildCount()>0)body=custom.getChildAt(0);
  String heading="";int topId=getResources().getIdentifier("topPanel","id","android");View top=d.findViewById(topId);TextView oldTitle=firstText(top);if(oldTitle!=null)heading=oldTitle.getText().toString();
  boolean customBody=body!=null;if(body==null){TextView message=d.findViewById(android.R.id.message);if(message!=null){ScrollView sv=new ScrollView(this);TextView copy=text(message.getText().toString(),KpaLayout.SECTION_TEXT,fg);copy.setPadding(dp(18),dp(12),dp(18),dp(12));sv.addView(copy);body=sv;}else if(d.getListView()!=null)body=d.getListView();else body=new View(this);}
  Object bodyTag=body.getTag();if(body.getParent() instanceof ViewGroup)((ViewGroup)body.getParent()).removeView(body);
  LinearLayout root=new LinearLayout(this);root.setTag("kpaDialog");root.setOrientation(1);root.setBackground(shape(bg));root.addView(dialogTitle(heading),new LinearLayout.LayoutParams(-1,dp(56)));root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);bar.setPadding(dp(12),dp(5),dp(12),dp(5));bar.setBackgroundColor(KpaTheme.BAR);
  for(int which:new int[]{AlertDialog.BUTTON_NEGATIVE,AlertDialog.BUTTON_NEUTRAL,AlertDialog.BUTTON_POSITIVE}){Button button=d.getButton(which);if(button==null||button.getVisibility()!=View.VISIBLE)continue;if(button.getParent() instanceof ViewGroup)((ViewGroup)button.getParent()).removeView(button);button.setAllCaps(false);button.setTextSize(KpaLayout.DIALOG_BUTTON_TEXT);button.setMinHeight(0);button.setMinimumHeight(0);button.setMinWidth(0);button.setMinimumWidth(0);button.setPadding(dp(18),0,dp(18),0);styleDialogButton(button,which);focusable(button);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(Math.max(dp(KpaLayout.DIALOG_BUTTON_MIN),(int)button.getPaint().measureText(button.getText().toString())+dp(40)),dp(KpaLayout.DIALOG_ACTION));bp.setMargins(dp(10),0,0,0);bar.addView(button,bp);}
  root.addView(bar,new LinearLayout.LayoutParams(-1,dp(KpaLayout.DIALOG_FOOTER)));d.setContentView(root);root.post(()->{View focused=d.getCurrentFocus();if(focused!=null&&focused.isClickable()&&inside(root,focused))return;ArrayList<View> choices=new ArrayList<>();collectFocusables(root,choices);if(!choices.isEmpty()){directionalSelection=true;selectFocus(choices.get(0));}});
  boolean full=fullDialog(heading);
  Window window=d.getWindow();if(full){root.setBackgroundColor(bg);window.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(bg));window.getDecorView().setPadding(0,0,0,0);window.setLayout(-1,-1);}
  else{int max=(int)(getResources().getDisplayMetrics().heightPixels*0.90);boolean browser=heading.startsWith("/storage/"),tallPicker=heading.equals("Roms存储")||heading.equals("选择文件夹")||heading.equals("选择 ZIP")||browser;int choices=bodyTag instanceof Integer?(Integer)bodyTag:0;float pickerRatio=browser?0.72f:choices<=1?0.48f:0.64f;int height=tallPicker?(int)(getResources().getDisplayMetrics().heightPixels*pickerRatio):customBody?max:Math.min(max,dp(260));if(!tallPicker&&bodyTag instanceof Integer&&(Integer)bodyTag<=2)height=Math.min(max,dp(116+44*(Integer)bodyTag));int width=(int)(getResources().getDisplayMetrics().widthPixels*(tallPicker?0.50:0.90));window.setLayout(width,height);window.setBackgroundDrawable(shape(bg));}

 }
 TextView firstText(View view){if(view instanceof TextView)return (TextView)view;if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++){TextView found=firstText(group.getChildAt(i));if(found!=null)return found;}}return null;}
 AlertDialog largeDialog(AlertDialog.Builder builder){AlertDialog d=builder.create();d.show();return d;}

 boolean defaultConfigure(AppSpec a){return a.supportsConfig&&(a==apps[0]||a==apps[1]||a.installed||a.apk!=null);}
 boolean defaultInstall(AppSpec a){return a.apk!=null;}
 boolean appsChanged(){for(AppSpec a:apps)if(a.install!=defaultInstall(a)||a.configure!=defaultConfigure(a))return true;return false;}
 boolean changed(String key){return getPreferences(0).getBoolean("changed."+key,false);}
 void markChoice(String key,File old,File next){String baseline=getPreferences(0).getString("default."+key,old==null?"":old.getAbsolutePath());getPreferences(0).edit().putString("default."+key,baseline).putBoolean("changed."+key,next!=null&&!next.getAbsolutePath().equals(baseline)).apply();}
 boolean optionChanged(String title){if(title.equals("应用选择"))return appsChanged();if(title.equals("资料目录"))return changed("config");if(title.equals("GBA整包"))return changed("gba");if(title.equals("Roms存储"))return !destination.equals(new File(SetupEngine.HOME));if(title.equals("覆盖资料"))return changed("main")||changed("android")||changed("lists");String[] names={"定制配置","安卓覆盖","游戏列表"},keys={"main","android","lists"};for(int i=0;i<names.length;i++)if(title.equals(names[i]))return changed(keys[i]);return false;}

 final class KeyBadge extends View {final String label;final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);KeyBadge(String value){super(MainActivity.this);label=value;paint.setTypeface(Typeface.DEFAULT_BOLD);paint.setTextAlign(Paint.Align.CENTER);}protected void onDraw(Canvas canvas){super.onDraw(canvas);float cx=getWidth()/2f,cy=getHeight()/2f;paint.setColor(fg);canvas.drawCircle(cx,cy,Math.min(cx,cy),paint);paint.setColor(bg);paint.setTextSize(dp(label.equals("+")?11:10));Paint.FontMetrics fm=paint.getFontMetrics();canvas.drawText(label,cx,cy-(fm.ascent+fm.descent)/2f,paint);}}
 View keyBadge(String label,Runnable action){View key=new KeyBadge(label);if(action!=null)key.setOnClickListener(v->action.run());return key;}
 void keyIcon(LinearLayout row,String label,Runnable action){View key=keyBadge(label,action);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(16),dp(16));lp.setMargins(label.equals("R")?dp(2):dp(10),0,label.equals("L")?0:dp(4),0);row.addView(key,lp);}
 void openLink(String url){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}
 void updateFooterLeft(){footerLeft.removeAllViews();TextView tip=text(footerNotice,KpaLayout.CAPTION_TEXT,footerColor);tip.setMaxLines(2);tip.setEllipsize(android.text.TextUtils.TruncateAt.END);if(step==3){LinearLayout credits=new LinearLayout(this);credits.setOrientation(0);credits.setGravity(Gravity.CENTER_VERTICAL);TextView maker=text("我不是矿神",KpaLayout.DETAIL_TEXT,accent);maker.setOnClickListener(v->openLink("https://imnks.com/"));credits.addView(maker);credits.addView(text("💗制作",KpaLayout.DETAIL_TEXT,muted));TextView divider=text("  ·  ",KpaLayout.CAPTION_TEXT,muted);credits.addView(divider);LinearLayout github=new LinearLayout(this);github.setGravity(Gravity.CENTER_VERTICAL);ImageView mark=new ImageView(this);mark.setImageDrawable(getDrawable(getResources().getIdentifier("ic_github","drawable",getPackageName())));LinearLayout.LayoutParams icon=new LinearLayout.LayoutParams(dp(14),dp(14));icon.setMargins(0,0,dp(5),0);github.addView(mark,icon);github.addView(text("KPA-Tools",KpaLayout.CAPTION_TEXT,muted));github.setOnClickListener(v->openLink("https://github.com/tbc0309/KPA-Tools"));credits.addView(github);footerLeft.addView(credits,new LinearLayout.LayoutParams(0,-2,1));}else footerLeft.addView(tip,new LinearLayout.LayoutParams(0,-2,1));tip.setOnClickListener(v->dialogBuilder().setTitle("提示详情").setMessage(footerNotice).setPositiveButton("关闭",null).show());}
 void footer(){if(footerRow!=null){updateFooterLeft();return;}LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(10),dp(5),dp(10),dp(5));row.setBackground(shape(KpaTheme.BAR));footerRow=row;footerLeft=new LinearLayout(this);footerLeft.setGravity(Gravity.CENTER_VERTICAL);row.addView(footerLeft,new LinearLayout.LayoutParams(0,-2,1));updateFooterLeft();LinearLayout keys=new LinearLayout(this);String[] labels={"A","B","X"};String[] names={"确定","返回","掌机管理"};for(int i=0;i<3;i++){View key=keyBadge(labels[i],null);LinearLayout.LayoutParams kp=new LinearLayout.LayoutParams(dp(16),dp(16));kp.setMargins(dp(10),0,dp(4),0);keys.addView(key,kp);TextView caption=text(names[i],KpaLayout.CAPTION_TEXT,fg);keys.addView(caption);final int n=i;key.setOnClickListener(v->controllerAction(n));caption.setOnClickListener(v->controllerAction(n));}LinearLayout guide=new LinearLayout(this);guide.setOrientation(1);guide.setGravity(Gravity.LEFT);LinearLayout navigation=new LinearLayout(this);navigation.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);keyIcon(navigation,"L",()->switchStep(-1));keyIcon(navigation,"R",()->switchStep(1));navigation.addView(text("步骤切换",KpaLayout.CAPTION_TEXT,fg));navigation.addView(new View(this),new LinearLayout.LayoutParams(0,1,1));keyIcon(navigation,"+",null);navigation.addView(text("按钮选择",KpaLayout.CAPTION_TEXT,fg));guide.addView(navigation,new LinearLayout.LayoutParams(-1,-2));guide.addView(keys,new LinearLayout.LayoutParams(-2,-2));keys.measure(View.MeasureSpec.makeMeasureSpec(0,View.MeasureSpec.UNSPECIFIED),View.MeasureSpec.makeMeasureSpec(0,View.MeasureSpec.UNSPECIFIED));int guideWidth=keys.getMeasuredWidth();navigation.setLayoutParams(new LinearLayout.LayoutParams(guideWidth,-2));row.addView(guide,new LinearLayout.LayoutParams(guideWidth,-2));LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,dp(KpaLayout.FOOTER));fp.setMargins(0,dp(8),0,0);rootShell.addView(row,fp);}
 void controllerAction(int n){if(interactionLocked())return;if(n==0){View selected=getCurrentFocus();if(directionalSelection&&selected!=null&&selected.isEnabled()&&selected.isClickable())selected.performClick();else if(primaryAction!=null)primaryAction.performClick();}else if(n==1)onBackPressed();else openRootPage();}
 void releaseControllerFocus(){directionalSelection=false;View focused=getCurrentFocus();if(focused!=null)focused.clearFocus();}
 void focusable(View view){view.setFocusable(true);view.setFocusableInTouchMode(true);view.setOnTouchListener((v,event)->{if(event.getAction()==MotionEvent.ACTION_DOWN){directionalSelection=false;v.setForeground(null);}return false;});view.setOnFocusChangeListener((v,has)->{if(has&&directionalSelection){GradientDrawable outline=shape(Color.TRANSPARENT);outline.setStroke(dp(KpaLayout.FOCUS_STROKE),KpaTheme.FOCUS);v.setForeground(outline);}else v.setForeground(null);});}
 void switchStep(int delta){if(interactionLocked()){toast("正在执行，请稍候");return;}int target=step+delta;if(target<0||target>3||target==step)return;if(target>0&&target!=3&&(!Environment.isExternalStorageManager()||!authorizationPassed())){toast("请先完成存储授权");return;}if(target==2&&!selectionReport.startsWith("✓")&&run==null){toast("资料检测通过后才能继续");return;}monitor.removeCallbacksAndMessages(null);if(step==2&&target==1&&run==null)discovered=false;step=target;save();render();if(step==1)autoDiscover();if(step==0)monitorAuthorization();if(step==2)monitorExecution();}
 boolean controllerKey(int code){return code==KeyEvent.KEYCODE_BUTTON_A||code==KeyEvent.KEYCODE_BUTTON_B||code==KeyEvent.KEYCODE_BUTTON_X||code==KeyEvent.KEYCODE_BUTTON_L1||code==KeyEvent.KEYCODE_BUTTON_R1||code==KeyEvent.KEYCODE_DPAD_UP||code==KeyEvent.KEYCODE_DPAD_DOWN||code==KeyEvent.KEYCODE_DPAD_LEFT||code==KeyEvent.KEYCODE_DPAD_RIGHT;}
 @Override public boolean dispatchKeyEvent(KeyEvent event){boolean dialogVisible=currentDialog!=null&&currentDialog.isShowing();int key=event.getKeyCode();if(dialogVisible&&(controllerKey(key)||key==KeyEvent.KEYCODE_BACK))return handleDialogKey(currentDialog,currentDialogTitle,key,event);if(!dialogVisible&&controllerKey(key)){if(event.getAction()==KeyEvent.ACTION_DOWN)return onKeyDown(key,event);return true;}return super.dispatchKeyEvent(event);}
 @Override public boolean onKeyDown(int code,KeyEvent event){if(getWindow().getDecorView().hasWindowFocus()&&controllerKey(code)){if(interactionLocked())return true;if(code==KeyEvent.KEYCODE_BUTTON_L1||code==KeyEvent.KEYCODE_BUTTON_R1){if(event.getRepeatCount()==0)switchStep(code==KeyEvent.KEYCODE_BUTTON_L1?-1:1);return true;}if(directionKey(code)){moveScreenFocus(code);return true;}if(event.getRepeatCount()==0)controllerAction(code==KeyEvent.KEYCODE_BUTTON_A?0:code==KeyEvent.KEYCODE_BUTTON_B?1:2);return true;}return super.onKeyDown(code,event);}
 @Override public boolean onKeyUp(int code,KeyEvent event){if(getWindow().getDecorView().hasWindowFocus()&&controllerKey(code))return true;return super.onKeyUp(code,event);}
 void tile(String name,String value,boolean ok){LinearLayout row=new LinearLayout(this);row.setPadding(dp(10),dp(4),dp(10),dp(4));boolean sourceTile=step==1&&(name.equals("资料目录")||name.equals("GBA整包")),storageTile=step==1&&name.equals("安装配置"),interactive=sourceTile||storageTile,optionalMissing=step==1&&name.equals("GBA整包")&&gba==null,deviceWarning=name.equals("设备型号")&&!deviceSupported();GradientDrawable tileStyle=shape(sourceTile&&!ok?buttonSurface:deviceWarning?KpaTheme.WARNING_SURFACE:KpaTheme.BAR);if(optionalMissing||deviceWarning)tileStyle.setStroke(dp(1),warningColor);row.setBackground(tileStyle);TextView title=text(name,KpaLayout.BODY_TEXT,optionalMissing||deviceWarning?warningColor:fg),detail=text(value,KpaLayout.DETAIL_TEXT,optionalMissing||deviceWarning?warningColor:ok?(sourceTile?fg:success):errorColor);if(optionChanged(name)||name.equals("安装配置")&&appsChanged()){title.setTextColor(errorColor);detail.setTextColor(errorColor);}detail.setSingleLine(true);detail.setEllipsize(android.text.TextUtils.TruncateAt.MIDDLE);row.addView(title,new LinearLayout.LayoutParams(dp(78),-2));row.addView(detail,new LinearLayout.LayoutParams(0,-2,1));if(interactive){TextView choose=text(storageTile?"存储选择":ok?"选择":"补选",KpaLayout.CAPTION_TEXT,optionalMissing?warningColor:ok?fg:warningColor);choose.setBackground(shape(optionalMissing?KpaTheme.WARNING_SURFACE:ok?buttonSurface:KpaTheme.WARNING_SURFACE));choose.setPadding(dp(8),dp(2),dp(8),dp(2));row.addView(choose);}LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(KpaLayout.TILE));lp.setMargins(0,dp(4),0,dp(4));content.addView(row,lp);if(interactive){focusable(row);row.setOnClickListener(v->{if(name.equals("资料目录")){pick(true,f->{markChoice("config",config,f);config=f;scanApps();sources.discover(f);invalidatePlan();save();autoDiscover();});}else if(name.equals("GBA整包"))chooseGba();else chooseStorage();});}}
 View compactChoice(String name,String value,boolean changed,Runnable action){LinearLayout box=new LinearLayout(this);box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(dp(12),dp(4),dp(12),dp(4));int changedColor=name.equals("Roms存储")?warningColor:errorColor;GradientDrawable style=shape(buttonSurface);style.setStroke(dp(1),changed?changedColor:KpaTheme.BORDER);box.setBackground(style);TextView title=text(name,KpaLayout.BODY_TEXT,changed?changedColor:fg),detail=text(value,KpaLayout.DETAIL_TEXT,changed?changedColor:success);detail.setGravity(Gravity.RIGHT);detail.setSingleLine(true);detail.setEllipsize(android.text.TextUtils.TruncateAt.END);box.addView(title,new LinearLayout.LayoutParams(0,-2,1));box.addView(detail,new LinearLayout.LayoutParams(-2,-2));if(action!=null){focusable(box);box.setOnClickListener(v->action.run());}return box;}
 void sourceChoices(int appsCount){LinearLayout row=new LinearLayout(this);View appsBox=compactChoice("安装配置",appsCount+" 款",appsChanged(),null),storageBox=compactChoice("Roms存储",storageName(),!destination.equals(new File(SetupEngine.HOME)),this::chooseStorage);LinearLayout.LayoutParams left=new LinearLayout.LayoutParams(0,dp(KpaLayout.TILE),1),right=new LinearLayout.LayoutParams(0,dp(KpaLayout.TILE),1);left.setMargins(0,dp(4),dp(4),dp(4));right.setMargins(dp(4),dp(4),0,dp(4));row.addView(appsBox,left);row.addView(storageBox,right);content.addView(row);}
 TextView executionState;
 boolean executionRunning(){try{return run!=null&&Arrays.asList("VALIDATING","CLEAN_APPS","INSTALL","CUSTOM","GBA","LISTS","RA_FIRST_LAUNCH","ANDROID","APPLY","VERIFY").contains(SetupEngine.read(new File(run,SetupEngine.STATUS)).trim());}catch(Exception ignored){return false;}}
 boolean interactionLocked(){return busy||executionRunning()&&!scriptDone();}
 void clearExecutionProtection(){monitor.removeCallbacks(heartbeat);if(wake!=null&&wake.isHeld())wake.release();wake=null;getWindow().clearFlags(WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON|WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);}
 boolean partialResult(){return initialPassed()&&(warningCount()>0||!verificationPassed()||gbaManual());}
 String executionLabel(){return initialPassed()?(partialResult()?"部分完成":"执行成功"):executionFailed()?"执行失败":(busy||executionRunning())?"执行中  "+String.format(Locale.US,"%.2f",preciseProgress)+"%":run!=null?"等待执行":"待执行";}
 int executionColor(){return initialPassed()?(warningCount()>0||!verificationPassed()||gbaManual()?warningColor:success):executionFailed()?errorColor:(busy||executionRunning())?runningColor:warningColor;}
 void setTextChanged(TextView view,String value){if(view!=null&&!value.contentEquals(view.getText()))view.setText(value);}
 void refreshExecutionState(){int stateColor=runningOverlayShown?KpaTheme.OVERLAY_TEXT:executionColor(),progressColor=runningOverlayShown?KpaTheme.OVERLAY_TEXT:stateColor;if(executionState!=null){if(!runningOverlayShown)setTextChanged(executionState,executionLabel());executionState.setTextColor(stateColor);}if(progressText!=null)progressText.setTextColor(progressColor);if(progressBar!=null)progressBar.setProgressTintList(android.content.res.ColorStateList.valueOf(runningOverlayShown?accent:progressColor));}
 void startStatusPulse(int color){statusPulseColor=color;statusPulseOn=false;monitor.removeCallbacks(statusPulse);monitor.post(statusPulse);}
 void resultCard(){LinearLayout result=new LinearLayout(this);result.setOrientation(1);result.setPadding(dp(14),dp(8),dp(14),dp(8));result.setBackground(shape(panel));result.addView(text("最终结果",KpaLayout.SECTION_TEXT,fg));boolean warned=warningCount()>0||!verificationPassed()||gbaManual();String summary=initialPassed()?(warned?"执行完成，发现 "+warningCount()+" 项提示":initialCount()+" 个文件核验通过"):"初始化失败，请查看执行日志";result.addView(text(summary,KpaLayout.BODY_TEXT,initialPassed()?(warned?warningColor:success):errorColor));if(initialPassed()&&gbaManual())result.addView(text("GBA整包请自行覆盖",KpaLayout.DETAIL_TEXT,warningColor));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(5),0,dp(3));screen.addView(result,lp);}
 android.graphics.drawable.Drawable stepBackground(boolean selected){if(!selected)return new android.graphics.drawable.ColorDrawable(Color.TRANSPARENT);GradientDrawable underline=shape(accent);underline.setCornerRadius(0);android.graphics.drawable.LayerDrawable layers=new android.graphics.drawable.LayerDrawable(new android.graphics.drawable.Drawable[]{underline});layers.setLayerGravity(0,Gravity.BOTTOM);layers.setLayerHeight(0,dp(2));return layers;}
 void createStepBar(){LinearLayout steps=new LinearLayout(this);String[] labels={"1 授权","2 资料","3 执行","关于"};for(int i=0;i<4;i++){TextView tab=text(labels[i],KpaLayout.BODY_TEXT,i==step?fg:muted);stepTabs[i]=tab;tab.setGravity(Gravity.CENTER);tab.setPadding(0,dp(8),0,dp(8));tab.setBackground(stepBackground(i==step));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(KpaLayout.STEP_BAR),1);lp.setMargins(i==0?0:dp(4),0,i==3?0:dp(4),0);steps.addView(tab,lp);final int target=i;focusable(tab);tab.setEnabled(!busy);tab.setOnClickListener(v->{if(!busy)switchStep(target-step);});}rootShell.addView(steps,0);}
 void updateStepBar(){for(int i=0;i<stepTabs.length;i++){stepTabs[i].setTextColor(i==step?fg:muted);stepTabs[i].setBackground(stepBackground(i==step));}}
 void render(){
  if(step==2&&executionRunning()&&!scriptDone()){if(!runningOverlayShown)showRunningOverlay();else pollRunningOverlay();return;}
  leaveRunningOverlay();
  monitor.removeCallbacks(statusPulse);executionState=null;logView=null;logScroll=null;progressText=null;progressBar=null;primaryAction=null;secondaryAction=null;directionalSelection=false;
  if(rootShell==null){footerRow=null;footerLeft=null;rootShell=new LinearLayout(this);rootShell.setBackgroundColor(bg);rootShell.setOrientation(1);rootShell.setPadding(dp(KpaLayout.EDGE),dp(8),dp(KpaLayout.EDGE),dp(8));screen=new LinearLayout(this);screen.setOrientation(1);rootShell.addView(screen,new LinearLayout.LayoutParams(-1,0,1));createStepBar();}else screen.removeAllViews();setContentView(rootShell);content=screen;
  updateStepBar();
  String notice=step==0?authorizationNotice():step==1?(discoveryRunning?"正在检测资料":selectionReport.isEmpty()?"等待自动识别资料":selectionReport.startsWith("✓")?"资料完整，可以继续":"资料不完整，请补选标红项目"):step==2?(initialPassed()?(partialResult()?"部分完成 · 点击执行日志查看":"执行成功 · 核验通过 "+initialCount()+" 个文件"):executionFailed()?"执行失败 · 点击执行日志查看":busy?"正在初始化 · 请保持本页":run!=null?"Root 脚本运行本批次脚本，完成后查看结果":"检查无误后确认执行"):"选择教程查看设置说明";
  hint(notice,executionFailed()&&step==2?errorColor:step==0&&!authorizationPassed()?warningColor:muted);
    switch(step){case 0:drawAuthorizationPage();break;case 1:drawSourcesPage();break;case 2:drawExecutionPage();break;default:drawAboutPage();}footer();


 }
 void optionCard(LinearLayout list,String title,String subtitle,Runnable action){LinearLayout item=new LinearLayout(this);item.setOrientation(1);item.setPadding(dp(16),dp(4),dp(16),dp(4));item.setBackground(shape(panel));item.addView(text(title+(optionChanged(title)?" · 已修改":""),KpaLayout.TITLE_TEXT,optionChanged(title)?errorColor:fg));boolean missing=subtitle.equals("未选择")||subtitle.equals("未找到")||subtitle.contains("缺少");if(missing)item.setBackground(shape(KpaTheme.WARNING_SURFACE));TextView t=text(subtitle,KpaLayout.DETAIL_TEXT,missing?warningColor:muted);t.setSingleLine(true);t.setEllipsize(android.text.TextUtils.TruncateAt.MIDDLE);if(!subtitle.isEmpty())item.addView(t);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(2),0,dp(2));list.addView(item,lp);focusable(item);item.setOnClickListener(v->action.run());}
 void drawAuthorizationPage(){card("设备授权",null,()->{tile("设备型号",deviceSupported()?"KONKR Pocket Advance":"未知机型，谨慎使用！",deviceSupported());tile("文件权限",Environment.isExternalStorageManager()?"已授权":"待授权",Environment.isExternalStorageManager());tile("存储 Root",authorizationPassed()?"已通过":"待执行",authorizationPassed());terminal("启动检查\n"+(deviceSupported()?"设备型号：KONKR Pocket Advance":"设备型号：未知机型，谨慎使用！")+"\n"+(Environment.isExternalStorageManager()?"文件权限：已授权":"文件权限：待授权")+"\n"+(authorizationPassed()?"存储 Root：已通过":"存储 Root：请运行 KPA_Authorize.sh"));actions("掌机管理",this::openRootPage,"下一步",()->{if(!authorizationPassed()||!Environment.isExternalStorageManager())return;step=1;save();render();autoDiscover();});});}
 void drawSourcesPage(){card("资料检测",null,()->{tile("资料目录",config==null?"":config.getName(),config!=null&&config.isDirectory()&&sources.mainZip!=null&&sources.mainZip.isFile());tile("GBA整包",gba==null?"未选择 · 可选":gba.getName(),true);int n=0;for(AppSpec app:apps)if(app.install)n++;sourceChoices(n);terminal(discoveryRunning?"自动检测\n正在搜索资料\n正在核对内容":"检测结果\n"+tailLog(selectionReport.isEmpty()?"等待自动检测":selectionReport)+"\n"+(selectionReport.startsWith("✓")?"资料完整":"请补全标红项目"));actions("调整选择",this::showSelectionOptions,discoveryRunning?"检测中":selectionReport.startsWith("✓")?"下一步":"补全资料",()->{if(!selectionReport.startsWith("✓")){showSelectionOptions();return;}step=2;progress=0;save();render();});});}
 void drawExecutionPage(){card(initialPassed()?"执行结果":"准备执行",null,()->{LinearLayout metrics=new LinearLayout(this);metrics.setGravity(Gravity.CENTER_VERTICAL);executionState=text(executionLabel(),KpaLayout.RESULT_TEXT,executionColor());metrics.addView(executionState,new LinearLayout.LayoutParams(0,-2,1));content.addView(metrics);boolean started=busy||run!=null||initialPassed()||executionFailed();if(started){boolean warned=partialResult();String metric=initialPassed()?(warned?"已处理 "+initialCount()+" 项":"核验 "+initialCount()+" 项"):currentWork.isEmpty()?"":currentWork+"  "+itemDone+" / "+itemTotal;progressText=text(metric,KpaLayout.ITEM_TEXT,executionColor());progressText.setGravity(Gravity.RIGHT);metrics.addView(progressText);progressBar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progressBar.setProgressTintList(android.content.res.ColorStateList.valueOf(executionColor()));progressBar.setMax(initialPassed()?100:itemTotal>0?itemTotal:100);progressBar.setProgress(initialPassed()?100:itemTotal>0?itemDone:progress);content.addView(progressBar,new LinearLayout.LayoutParams(-1,dp(10)));}terminal(executionDisplayLog());if(initialPassed()){boolean warned=partialResult();String result=warned?"部分完成":"执行成功";int color=warned?warningColor:success;actions("执行日志",this::showLog,result,()->{});primaryAction.setEnabled(false);primaryAction.setClickable(false);primaryAction.setFocusable(false);primaryAction.setAlpha(1f);startStatusPulse(color);}else if(!busy){if(executionFailed()){actions("返回选择",()->{step=1;save();render();},"执行失败",()->{});primaryAction.setEnabled(false);primaryAction.setClickable(false);primaryAction.setFocusable(false);primaryAction.setAlpha(1f);startStatusPulse(errorColor);}else if(run==null)actions("返回选择",()->{step=1;save();render();},"确认执行",this::confirmExecution);else actions("掌机管理",this::openRootPage,"查看结果",()->task(this::readRootResult));}});}
 String executionDisplayLog(){if(run!=null&&initialPassed())return tailLog(operationLog());if(run!=null||getPreferences(0).getBoolean("executionConfirmed",false))return getPreferences(0).getString("lastLog","执行准备\n等待确认");String value=getPreferences(0).getString("checkLog","").trim();return value.isEmpty()?"本次检查\n"+spaceReport+"\n"+(selectionReport.isEmpty()?"等待资料检测":selectionReport):value;}
 boolean extracting(){return run==null||!new File(run,SetupEngine.STATUS).isFile();}
 void showRunningOverlay(){runningOverlayShown=true;preciseProgress=Math.max(preciseProgress,progress);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_STABLE);LinearLayout page=new LinearLayout(this);page.setOrientation(1);page.setGravity(Gravity.CENTER);page.setPadding(dp(54),dp(40),dp(54),dp(40));page.setBackgroundColor(KpaTheme.OVERLAY_BG);executionState=text(currentWork.isEmpty()?"正在初始化":currentWork,KpaLayout.OVERLAY_TITLE_TEXT,KpaTheme.OVERLAY_TEXT);executionState.setTypeface(null,Typeface.BOLD);executionState.setGravity(Gravity.CENTER);page.addView(executionState,new LinearLayout.LayoutParams(-1,-2));progressText=text(extracting()?"解压中，请耐心等待":preciseProgressText(),KpaLayout.OVERLAY_PROGRESS_TEXT,KpaTheme.OVERLAY_TEXT);progressText.setGravity(Gravity.CENTER);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,-2);pp.setMargins(0,dp(10),0,dp(10));page.addView(progressText,pp);progressBar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progressBar.setMax(10000);progressBar.setProgress((int)(preciseProgress*100));progressBar.setProgressTintList(android.content.res.ColorStateList.valueOf(accent));progressBar.setVisibility(extracting()?View.INVISIBLE:View.VISIBLE);page.addView(progressBar,new LinearLayout.LayoutParams(-1,dp(5)));logView=text("正在准备，请勿关机",KpaLayout.SECTION_TEXT,warningColor);logView.setGravity(Gravity.CENTER);logView.setMaxLines(4);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(16),0,0);page.addView(logView,lp);setContentView(page);}
 void leaveRunningOverlay(){if(!runningOverlayShown)return;runningOverlayShown=false;Window window=getWindow();window.clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);window.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);}
 String lastLogLine(String value){String[] lines=value.replace('\r','\n').split("\n");for(int i=lines.length-1;i>=0;i--)if(!lines[i].trim().isEmpty())return lines[i].trim();return "正在准备";}
 String runningPhase(String state,String raw){if(state.equals("VALIDATING"))return "校验资料";if(state.equals("CLEAN_APPS"))return "清理旧配置";if(state.equals("CUSTOM"))return "导入定制配置";if(state.equals("GBA"))return "导入 GBA整包";if(state.equals("LISTS"))return "覆盖游戏列表";if(state.equals("RA_FIRST_LAUNCH"))return "初始化 RA";if(state.equals("ANDROID")||state.equals("APPLY"))return "覆盖安卓目录";if(state.equals("VERIFY"))return "核验文件";if(state.equals("DONE"))return "初始化完成";if(state.equals("INSTALL")){int at=raw.lastIndexOf("Installing:");String latest=at<0?"":raw.substring(at);if(latest.startsWith("Installing: org.pegasus_frontend.android"))return "安装天马G";if(latest.startsWith("Installing: com.retroarch.aarch64"))return "安装 RA";return "安装其他应用";}return currentWork.isEmpty()?"正在初始化":currentWork;}
 String preciseProgressText(){return "总进度  "+String.format(Locale.US,"%.2f",Math.min(100,preciseProgress))+"%";}
 void pollRunningOverlay(){if(extracting()){setTextChanged(progressText,"解压中，请耐心等待");if(progressBar!=null)progressBar.setVisibility(View.INVISIBLE);return;}if(run!=null)try{String state=SetupEngine.read(new File(run,SetupEngine.STATUS)).trim();File ip=new File(run,"item-progress.txt");if(ip.isFile()){String[] p=SetupEngine.read(ip).trim().split("\t",3);if(p.length==3){currentWork=p[0];itemDone=Math.max(0,Integer.parseInt(p[1]));itemTotal=Math.max(1,Integer.parseInt(p[2]));preciseProgress=Math.max(preciseProgress,Math.min(99.0,99.0*itemDone/itemTotal));}}if(state.equals("VERIFY"))preciseProgress=99.99;else if(state.equals("DONE"))preciseProgress=100.0;else preciseProgress=Math.min(99.0,preciseProgress);File log=new File(run,SetupEngine.EXECUTION_LOG);String raw=log.isFile()?SetupEngine.read(log):"";currentWork=runningPhase(state,raw);String message=raw.isEmpty()?lastLogLine(getPreferences(0).getString("lastLog","正在准备")):lastLogLine(chineseLog(raw));setTextChanged(logView,message);if(logView!=null)logView.setTextColor(logColor(message));setTextChanged(executionState,currentWork);if(executionState!=null)executionState.setTextColor(KpaTheme.OVERLAY_TEXT);}catch(Exception ignored){}setTextChanged(progressText,preciseProgressText());if(progressText!=null)progressText.setTextColor(KpaTheme.OVERLAY_TEXT);if(progressBar!=null){progressBar.setVisibility(View.VISIBLE);if(progressBar.getMax()!=10000)progressBar.setMax(10000);int value=(int)Math.round(preciseProgress*100);if(progressBar.getProgress()!=value)progressBar.setProgress(value);}}
 void monitorRunningOverlay(){if(step!=2||!executionRunning()||scriptDone()){clearExecutionProtection();leaveRunningOverlay();render();return;}pollRunningOverlay();monitor.postDelayed(this::monitorRunningOverlay,1000);}
 void drawAboutPage(){String version="";try{version=getPackageManager().getPackageInfo(getPackageName(),0).versionName;}catch(Exception ignored){}LinearLayout parent=content;LinearLayout about=new LinearLayout(this);about.setOrientation(1);about.setGravity(Gravity.CENTER_VERTICAL);parent.addView(about,new LinearLayout.LayoutParams(-1,0,1));content=about;card("设置教程",null,()->{actions("手柄配置教程",()->openTutorial(true),"模拟器设置教程",()->openTutorial(false));});final String current=version;card("",null,()->{TextView name=text("KPA助手  "+current,KpaLayout.APP_TITLE_TEXT,fg);name.setTypeface(null,Typeface.BOLD);content.addView(name);TextView build=text("构建 "+BuildInfo.TIME+"  ·  com.imnks.kpatools  ·  API 30–35  ·  Release",KpaLayout.META_TEXT,muted);build.setSingleLine(true);build.setGravity(Gravity.CENTER_VERTICAL);build.setPadding(0,0,0,0);content.addView(build);TextView intro=text("为 KONKR Pocket Advance 安装应用、导入配置与整理游戏资料。",KpaLayout.BODY_TEXT,fg);intro.setPadding(0,dp(23),0,dp(4));content.addView(intro);add("© 2026 我不是矿神。本助手用于安装与配置整理，第三方应用、配置、教程及游戏内容的版权归各自作者与权利人所有。",KpaLayout.CAPTION_TEXT,muted);});content=parent;}
 void finishSelection(){render();if(step==1&&!selectionReport.startsWith("✓"))autoDiscover();}
 void returnToSources(){step=1;save();render();if(!selectionReport.startsWith("✓"))autoDiscover();}
 String appChoiceSummary(){int install=0;for(AppSpec app:apps)if(app.install)install++;return install+" 款安装";}
 String importChoiceSummary(){return "定制"+(sources.mainZip==null?"缺少":"✓")+" · 安卓"+(sources.androidZip==null?"缺少":"✓")+" · 列表"+(sources.lists==null?"缺少":"✓");}
 void showSelectionOptions(){LinearLayout list=new LinearLayout(this);list.setOrientation(1);list.setPadding(dp(12),dp(8),dp(12),dp(8));final AlertDialog[] dialog=new AlertDialog[1];java.util.function.Consumer<Runnable> go=a->changeDialog(dialog[0],a);optionCard(list,"资料目录",config==null?"未找到":config.getName(),()->go.accept(()->pick(true,f->{markChoice("config",config,f);config=f;scanApps();sources.discover(f);invalidatePlan();save();autoDiscover();})));optionCard(list,"GBA整包",gba==null?"未选择 · 可选":gba.getName(),()->go.accept(this::chooseGba));optionCard(list,"覆盖资料",importChoiceSummary(),()->go.accept(this::showImportOptions));optionCard(list,"应用选择",appChoiceSummary(),()->go.accept(this::showApplications));optionCard(list,"Roms存储",storageName()+" · 游戏与列表",()->go.accept(this::chooseStorage));ScrollView sv=new ScrollView(this);sv.setBackgroundColor(bg);sv.addView(list);dialog[0]=dialogBuilder().setCustomTitle(dialogTitle("调整选择")).setView(sv).setNegativeButton("返回",(d,w)->{finishSelection();}).create();dialog[0].show();}
 boolean executionFailed(){if(!getPreferences(0).getString("executionError", "").isEmpty())return true;try{return run!=null&&SetupEngine.read(new File(run,SetupEngine.STATUS)).trim().equals("ERROR");}catch(Exception ignored){return false;}}
 boolean gbaManual(){try{return run!=null&&SetupEngine.read(new File(run,SetupEngine.GBA_STATUS)).trim().equals("MANUAL");}catch(Exception ignored){return false;}}
 void openTutorial(boolean controller){startActivity(new Intent(this,TutorialActivity.class).putExtra("controller",controller));}
 File authorizationReceipt(){return new File(SetupEngine.WORK_ROOT,"authorization/"+getPackageName()+"-"+authorizationToken+".ok");}
 boolean authorizationPassed(){try{return !authorizationToken.isEmpty()&&SetupEngine.read(authorizationReceipt()).trim().equals(authorizationToken);}catch(Exception ignored){return false;}}
 void generateAuthorization(){if(!Environment.isExternalStorageManager())return;if(authorizationPassed()){new File(SetupEngine.HOME,"KPA_Authorize.sh").delete();return;}try{SetupEngine.mkdir(authorizationReceipt().getParentFile());String path=RootBridge.q(authorizationReceipt().getAbsolutePath()),authDir=RootBridge.q(authorizationReceipt().getParentFile().getAbsolutePath());String script="#!/system/bin/sh\nif [ \"$(id -u)\" != 0 ]; then echo 'ERROR: Root permission missing.'; exit 1; fi\nmkdir -p "+authDir+"\nif ! cmd appops set --uid "+getPackageName()+" MANAGE_EXTERNAL_STORAGE allow; then echo 'ERROR: Storage permission grant failed.'; exit 1; fi\nif ! printf '%s\\n' "+RootBridge.q(authorizationToken)+" > "+path+" || [ \"$(cat "+path+")\" != "+RootBridge.q(authorizationToken)+" ]; then echo 'ERROR: Authorization receipt verification failed.'; exit 1; fi\necho 'SUCCESS: Storage Root authorized.'\n";SetupEngine.write(new File(SetupEngine.HOME,"KPA_Authorize.sh"),script);}catch(Exception e){toast("授权脚本生成失败："+e.getMessage());}} void confirmExecution(){if(!authorizationPassed()){step=0;save();render();toast("先执行存储 Root 授权脚本");return;}dialogBuilder().setTitle("最终确认执行").setMessage(applicationSelection()+" 清理旧配置 · 覆盖资料 · 不备份"+(skipGbaExpected?" · GBA 自行覆盖":"")).setNegativeButton("取消",null).setPositiveButton("确认开始",(d,w)->{finalized=false;progress=0;preciseProgress=0;itemDone=0;itemTotal=0;progressPhase="";displayedLogTimes.clear();getPreferences(0).edit().putInt("progress",0).putBoolean("executionConfirmed",true).remove("executionError").putString("lastLog",chineseLog("用户已确认，开始检查执行条件")).apply();task(()->{prepareBatch();executeBatch();});}).show();}
 void autoDiscover(){if(!Environment.isExternalStorageManager()||discoveryRunning||discovered||busy)return;if(config!=null&&!config.isDirectory())config=null;if(gba!=null&&(!gba.isFile()||!gba.canRead()))gba=null;discoveryRunning=true;render();executor.execute(()->{ArrayList<File> configs=new ArrayList<>(),games=new ArrayList<>();boolean gbaSkipped=getPreferences(0).getBoolean("gbaSkipped",false);if(config==null||gba==null&&!gbaSkipped){StorageManager sm=(StorageManager)getSystemService(STORAGE_SERVICE);for(StorageVolume v:sm.getStorageVolumes())if(v.getDirectory()!=null)discoverTree(v.getDirectory(),0,configs,games);}String report="";try{if(config==null||!config.isDirectory()){if(configs.size()==1){config=configs.get(0);scanApps();sources.discover(config);}else report=configs.isEmpty()?"未找到资料目录，请手动选择":"发现多个资料目录，请手动确认";}if(!gbaSkipped&&(gba==null||!gba.isFile())){if(games.size()==1)gba=games.get(0);else if(games.size()>1)report+="\n发现多个 GBA整包，请手动确认";}if(report.trim().isEmpty()||report.trim().startsWith("发现多个 GBA")){if(sources.mainZip==null||!sources.mainZip.isFile()||sources.androidZip==null||!sources.androidZip.isFile()){File main=sources.mainZip,android=sources.androidZip,lists=sources.lists;sources.discover(config);if(main!=null&&main.isFile())sources.mainZip=main;if(android!=null&&android.isFile())sources.androidZip=android;if(lists!=null&&lists.isDirectory())sources.lists=lists;}detectSelection();report="✓ 资料自动识别完成\n"+spaceReport+(skipGbaExpected?"\n空间不足：继续安装应用与覆盖配置，GBA 请自行覆盖":"");}}catch(Exception e){report="资料检测失败："+e.getMessage();}final String result=report;runOnUiThread(()->{selectionReport=result;discoveryRunning=false;discovered=true;save();render();});});}
 void discoverTree(File dir,int depth,List<File> configs,List<File> games){if(depth>4||dir.getName().equals("Android")||dir.getName().equals("KPA-Tools")||dir.getName().equals("PegasusG-Setup")||dir.getName().equals("Roms"))return;File[] files=dir.listFiles();if(files==null)return;for(File f:files){if(f.isDirectory()&&!f.getName().startsWith("."))discoverTree(f,depth+1,configs,games);else if(f.isFile()&&f.getName().toLowerCase(Locale.ROOT).endsWith(".zip")){int kind=SourceDiscovery.kind(f);if(kind==1){File root=SourceDiscovery.bundleRoot(f);if(!configs.contains(root))configs.add(root);}else if(kind==2&&!games.contains(f))games.add(f);}}}

 void updateProgress(int n){refreshExecutionState();int next=Math.max(progress,Math.min(100,n));if(next!=progress)getPreferences(0).edit().putInt("progress",next).apply();progress=next;if(runningOverlayShown){preciseProgress=Math.max(preciseProgress,Math.min(initialPassed()?100.0:99.99,n));setTextChanged(progressText,preciseProgressText());if(progressBar!=null){progressBar.setMax(10000);progressBar.setProgress((int)Math.round(preciseProgress*100));}return;}String label=initialPassed()?"核验 "+initialCount()+" 项":"总进度  "+progress+"%";setTextChanged(progressText,label);if(progressBar!=null){if(progressBar.getMax()!=100)progressBar.setMax(100);if(progressBar.getProgress()!=progress)progressBar.setProgress(progress);}}
 String tailLog(String value){String[] lines=value.split("\n");StringBuilder out=new StringBuilder();for(int i=Math.max(0,lines.length-7);i<lines.length;i++){String l=lines[i];out.append(l.length()>95?l.substring(0,92)+"…":l).append("\n");}return out.toString().trim();}
 void monitorAuthorization(){if(step!=0||isFinishing())return;boolean passed=authorizationPassed();if(passed!=authorizationObserved){authorizationObserved=passed;if(!busy)render();}monitor.postDelayed(this::monitorAuthorization,1000);}
 void monitorExecution(){if(step!=2||run==null)return;try{File st=new File(run,SetupEngine.STATUS);String state=st.isFile()?SetupEngine.read(st).trim():"";if(state.equals("DONE")){preciseProgress=100;progress=100;if(progressText!=null)setTextChanged(progressText,"核验 "+initialCount()+" 项");if(progressBar!=null){progressBar.setMax(100);progressBar.setProgress(100);}if(!busy&&!finalized)task(this::readRootResult);return;}File ip=new File(run,"item-progress.txt");if(ip.isFile()){String[] p=SetupEngine.read(ip).trim().split("\t",3);if(p.length==3){currentWork=p[0];itemDone=Math.max(0,Integer.parseInt(p[1]));itemTotal=Math.max(1,Integer.parseInt(p[2]));preciseProgress=Math.max(preciseProgress,Math.min(99.0,99.0*itemDone/itemTotal));}}if(state.equals("VERIFY"))preciseProgress=99.99;progress=(int)preciseProgress;if(progressText!=null)progressText.setText(preciseProgressText());if(progressBar!=null){progressBar.setMax(10000);progressBar.setProgress((int)Math.round(preciseProgress*100));}File log=new File(run,SetupEngine.EXECUTION_LOG);if(log.isFile()&&logView!=null){String t=SetupEngine.read(log);styleLog(tailLog(t));scrollLog();}if(state.equals("ERROR")){getPreferences(0).edit().putString("lastLog",logView==null?"初始化失败，请检查执行日志":logView.getText().toString()).apply();return;}}catch(Exception ignored){}monitor.postDelayed(this::monitorExecution,1000);}

 String applicationSelection(){int install=0;for(AppSpec a:apps)if(a.install)install++;return "安装 / 更新 "+install+" 款。";}
 void openHandheld(){try{Intent i=new Intent();i.setComponent(new ComponentName("com.ayaneo.home","com.ayaneo.settings.ui.global.SettingMainActivity"));i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);startActivity(i);}catch(Exception e){toast("掌机助手设置入口不可用，请从系统应用列表打开掌机助手");}}
 void openRootPage(){openHandheld();rootPageGuide();}
 void rootPageGuide(){rootGuideActive=true;rootGuideUntil=SystemClock.uptimeMillis()+ROOT_GUIDE_MS;rootGuideHandler.removeCallbacks(rootGuideRepeat);rootGuideRepeat.run();}
 void stopRootPageGuide(){rootGuideActive=false;rootGuideHandler.removeCallbacks(rootGuideRepeat);if(rootGuideToast!=null){rootGuideToast.cancel();rootGuideToast=null;}}
 String operationLog(){String value=getPreferences(0).getString("lastLog","等待操作。");if(run!=null)try{File rootLog=new File(run,SetupEngine.EXECUTION_LOG);if(rootLog.isFile())value=chineseLog(SetupEngine.read(rootLog));File details=new File(run,SetupEngine.DETAILS);if(details.isFile()&&!verificationPassed()){StringBuilder failed=new StringBuilder();for(String line:SetupEngine.read(details).split("\n"))if(!line.trim().isEmpty()&&!line.endsWith(": OK"))failed.append(line).append('\n');if(failed.length()>0)value+="\n\n核验未通过明细：\n"+failed;}}catch(Exception ignored){}return value.trim();}
 void showLog(){TextView t=text(operationLog(),KpaLayout.DETAIL_TEXT,fg);t.setTextIsSelectable(true);ScrollView v=new ScrollView(this);v.setPadding(dp(14),dp(8),dp(14),dp(8));v.addView(t);dialogBuilder().setTitle("操作记录").setView(v).setPositiveButton("关闭",null).show();}
 void showApplications(){
  LinearLayout list=new LinearLayout(this);list.setOrientation(1);list.setPadding(dp(16),dp(8),dp(16),dp(8));
  for(AppSpec a:apps){LinearLayout group=new LinearLayout(this);group.setOrientation(1);group.setPadding(dp(10),dp(6),dp(10),dp(6));group.setBackground(shape(panel));LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,-2);gp.setMargins(0,dp(4),0,dp(4));list.addView(group,gp);String state=a.installed?"已安装":"未安装";TextView title=text(a.label+"  ·  "+state,KpaLayout.SECTION_TEXT,fg);android.text.SpannableString titleText=new android.text.SpannableString(title.getText());titleText.setSpan(new android.text.style.ForegroundColorSpan(a.installed?success:warningColor),titleText.length()-state.length(),titleText.length(),android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);title.setText(titleText);group.addView(title);if(initialStates.containsKey(a.pkg)){TextView note=text(initialStates.get(a.pkg),KpaLayout.CAPTION_TEXT,muted);note.setSingleLine(true);note.setEllipsize(android.text.TextUtils.TruncateAt.END);group.addView(note);}TextView archive=text(a.apk==null?"补选安装":"安装包 · "+a.apk.getName(),KpaLayout.CAPTION_TEXT,a.apk==null?warningColor:muted);archive.setSingleLine(true);archive.setEllipsize(android.text.TextUtils.TruncateAt.MIDDLE);archive.setPadding(dp(8),dp(6),dp(8),dp(6));archive.setBackground(shape(a.apk==null?KpaTheme.WARNING_SURFACE:buttonSurface));group.addView(archive);archive.setOnClickListener(v->changeDialog(currentDialog,()->pick(false,f->{PackageInfo info=getPackageManager().getPackageArchiveInfo(f.getAbsolutePath(),0);if(info==null||!a.pkg.equals(info.packageName)){toast("安装包不属于所选软件");showApplications();return;}a.apk=f;a.install=true;getPreferences(0).edit().putString("apk."+a.pkg,f.getAbsolutePath()).apply();invalidatePlan();save();showApplications();})));LinearLayout row=new LinearLayout(this);group.addView(row);
   CheckBox install=new CheckBox(this);install.setText("安装更新");install.setTextColor(a.install!=defaultInstall(a)?errorColor:fg);install.setButtonTintList(android.content.res.ColorStateList.valueOf(a.install!=defaultInstall(a)?errorColor:accent));install.setChecked(a.install);install.setEnabled(a.apk!=null);row.addView(install,new LinearLayout.LayoutParams(0,-2,1));install.setOnCheckedChangeListener((b,v)->{a.install=v;install.setTextColor(v!=defaultInstall(a)?errorColor:fg);install.setButtonTintList(android.content.res.ColorStateList.valueOf(v!=defaultInstall(a)?errorColor:accent));invalidatePlan();save();});
  }ScrollView sv=new ScrollView(this);sv.setBackgroundColor(bg);sv.addView(list);largeDialog(dialogBuilder().setCustomTitle(dialogTitle("应用选择")).setView(sv).setNegativeButton("返回",(d,w)->{showSelectionOptions();}).setPositiveButton("完成",(d,w)->{showSelectionOptions();}));
 }
 void showImportOptions(){LinearLayout list=new LinearLayout(this);list.setOrientation(1);list.setPadding(dp(12),dp(6),dp(12),dp(6));final AlertDialog[] dialog=new AlertDialog[1];String[] titles={"定制配置","安卓覆盖","游戏列表"};File[] files={sources.mainZip,sources.androidZip,sources.lists};String[] kinds={"main","android","lists"};for(int i=0;i<titles.length;i++){final int n=i;optionCard(list,titles[i],files[i]==null?"未选择":files[i].getName(),()->changeDialog(dialog[0],()->{if(n==2)pick(true,f->{markChoice("lists",sources.lists,f);sources.lists=f;invalidatePlan();save();render();});else chooseZip(kinds[n]);}));}ScrollView sv=new ScrollView(this);sv.setBackgroundColor(bg);sv.addView(list);dialog[0]=dialogBuilder().setCustomTitle(dialogTitle("覆盖资料")).setView(sv).setNegativeButton("返回",(d,w)->{showSelectionOptions();}).create();dialog[0].show();}
 void detectSelection()throws Exception {
  boolean preview=!getPreferences(0).getBoolean("executionConfirmed",false);if(preview)beginCheckLog();
  if(config==null||!config.isDirectory())throw new Exception("请选择完整资料文件夹");
  if(gba!=null&&(!gba.isFile()||SourceDiscovery.kind(gba)!=2))throw new Exception("所选 ZIP 内未识别到 GBA 游戏和列表结构");
  if(sources.mainZip==null||!sources.mainZip.isFile())throw new Exception("未找到定制主配置 ZIP，请在导入选项选择");
  if(SourceDiscovery.kind(sources.mainZip)!=1)throw new Exception("主配置缺少天马G或 RA 配置，请补选");
  if(sources.androidZip==null||!sources.androidZip.isFile()||SourceDiscovery.kind(sources.androidZip)!=3)throw new Exception("缺少有效安卓覆盖配置，请补选");
  for(AppSpec a:apps){if(a.install&&(a.apk==null||!a.apk.isFile()))throw new Exception("缺少 "+a.label+" 安装包");if(a.configure&&!a.installed&&!a.install)throw new Exception("请勾选安装 "+a.label+"，或取消导入配置");}
  if(gba!=null&&(!apps[0].configure||!apps[1].configure))throw new Exception("导入 GBA 必须选择天马G与 RA 的配置");long available=new android.os.StatFs(destination.getAbsolutePath()).getAvailableBytes();SetupEngine.SpaceEstimate quote=SetupEngine.estimateSpace(sources.mainZip,gba,sources,apps,destination);skipGbaExpected=gba!=null&&!quote.includes(available);spaceReport=storageName()+"可用 "+SetupEngine.gb(available)+" GiB · 预计解压 "+SetupEngine.gb(quote.full)+" GiB"+(gba==null?" · 未选GBA":"");recordCheck("空间检查："+spaceReport+"（仅导入文件，不计应用安装大小）",preview);auditConfigs(preview);runOnUiThread(()->selectionReport="✓ 必备资料与应用已确认");recordCheck(gba==null?"资料检测通过，本次跳过 GBA整包":"资料与应用检测通过",preview);
 }
 void prepareBatch()throws Exception {run=null;engine=null;save();line("存储 Root 授权有效");detectSelection();SetupEngine next=new SetupEngine(this,config,gba,destination,apps,this::line,getPreferences(0).getString("resumeRun", "").isEmpty()?null:new File(getPreferences(0).getString("resumeRun", "")));next.sources=sources;sources.grantStorage=true;run=next.run;save();File ready=next.prepare();new File(ready,"item-progress.txt").delete();getPreferences(0).edit().remove("resumeRun").apply();engine=next;run=ready;save();line("资料准备完成，等待运行 Root 脚本");}
 void executeBatch()throws Exception {if(engine==null){line("请在掌机助手运行已生成的本批次脚本，或返回重新准备。");runOnUiThread(()->showRootInstructions("setup"));return;}runOnUiThread(()->monitor.postDelayed(this::monitorRunningOverlay,500));if(engine.execute())readRootResult();else runOnUiThread(()->showRootInstructions("setup"));}
 boolean initialPassed(){try{return run!=null&&SetupEngine.read(new File(run,SetupEngine.STATUS)).trim().equals("DONE");}catch(Exception e){return false;}}
 boolean verificationPassed(){try{return run!=null&&SetupEngine.read(new File(run,SetupEngine.RESULT)).contains("执行状态：成功");}catch(Exception e){return false;}}
 int warningCount(){try{for(String l:SetupEngine.read(new File(run,SetupEngine.RESULT)).split("\n"))if(l.startsWith("提醒数量："))return Integer.parseInt(l.substring(5).trim());}catch(Exception ignored){}return 0;}
 int initialCount(){try{for(String l:SetupEngine.read(new File(run,SetupEngine.RESULT)).split("\n"))if(l.startsWith("核验文件："))return Integer.parseInt(l.substring(5).trim());}catch(Exception e){}return 0;}
 void showManualApps(){String[] names=Arrays.stream(apps).filter(a->a.configure).map(a->a.label+(permissionPassed(a.pkg)?" · 系统权限通过":" · 权限待确认")).toArray(String[]::new);AppSpec[] selected=Arrays.stream(apps).filter(a->a.configure).toArray(AppSpec[]::new);dialogBuilder().setTitle("最后授权与配置").setItems(names,(d,n)->{AppSpec a=selected[n];dialogBuilder().setTitle(a.label).setMessage(requirements(a.pkg)).setPositiveButton("打开应用",(di,w)->launch(a.pkg)).setNeutralButton("目录已确认",(di,w)->{manualDirectory.put(a.pkg,true);save();render();}).setNegativeButton("返回",null).show();}).setNegativeButton("关闭",null).show();}

 interface Work {void run() throws Exception;}
 void task(Work w){if(busy)return;busy=true;if(step==2)showRunningOverlay();else render();
  wake=((PowerManager)getSystemService(POWER_SERVICE)).newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"PegasusG:setup");wake.acquire(6*60*60*1000L);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON|WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON);monitor.removeCallbacks(heartbeat);monitor.post(heartbeat);
  executor.execute(()->{try{w.run();}catch(Throwable e){boolean execution=step==2&&getPreferences(0).getBoolean("executionConfirmed",false);if(execution)getPreferences(0).edit().putString("executionError",String.valueOf(e.getMessage())).apply();line("✕ "+e.getMessage());if(!execution)runOnUiThread(()->dialogBuilder().setTitle("步骤未完成").setMessage(e.getMessage()+"\n\n执行日志已保留，请检查失败原因。").setPositiveButton("知道了",null).show());}
   finally{runOnUiThread(()->{busy=false;clearExecutionProtection();getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);rootShell=null;screen=null;render();});}});
 }
 void beginCheckLog(){displayedLogTimes.clear();getPreferences(0).edit().putString("checkLog","").apply();}
 void recordCheck(String value,boolean preview){if(!preview){line(value);return;}String message=chineseLog(value),previous=getPreferences(0).getString("checkLog","");String next=previous.isEmpty()?message:previous+"\n"+message;getPreferences(0).edit().putString("checkLog",next).apply();}
 void line(String s){
  runOnUiThread(()->{if(s.startsWith("@ITEM\t")){String[] p=s.split("\t",4);if(p.length==4){currentWork=p[1].replace("配置资料","准备配置").replace("GBA整包","准备 GBA");itemDone=Integer.parseInt(p[2]);itemTotal=Math.max(1,Integer.parseInt(p[3]));setTextChanged(executionState,currentWork);setTextChanged(progressText,"解压中，请耐心等待");if(progressBar!=null)progressBar.setVisibility(View.INVISIBLE);}return;}String prev=getPreferences(0).getString("lastLog","");String message=chineseLog(s),next=prev+"\n"+message;if(next.length()>16000)next=next.substring(next.length()-16000);getPreferences(0).edit().putString("lastLog",next).apply();if(logView!=null){if(step==2&&busy){String latest=lastLogLine(message);setTextChanged(logView,latest);logView.setTextColor(logColor(latest));}else{styleLog(tailLog(next));scrollLog();}}});
 }
 void storagePermission(){try{startActivity(new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION,Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION));}}
 interface Chosen {void accept(File f);}
 void chooseGba(){chooseZip("gba");}
 String storageName(){return destination.getAbsolutePath().equals(SetupEngine.HOME)?"内部存储":"TF 卡";}
 void chooseStorage(){StorageManager sm=(StorageManager)getSystemService(STORAGE_SERVICE);ArrayList<File> roots=new ArrayList<>();ArrayList<String> labels=new ArrayList<>();roots.add(new File(SetupEngine.HOME));labels.add(SetupEngine.HOME);for(StorageVolume volume:sm.getStorageVolumes()){File root=volume.getDirectory();if(root==null||root.getAbsolutePath().equals(SetupEngine.HOME)||!root.isDirectory())continue;roots.add(root);labels.add(root.getAbsolutePath());}String[] choices=labels.toArray(new String[0]);largeDialog(dialogBuilder().setCustomTitle(dialogTitle("Roms存储")).setView(choiceView(choices,(d,w)->{if(w<0||w>=roots.size())return;File next=roots.get(w);markChoice("destination",destination,next);destination=next;invalidatePlan();save();render();autoDiscover();})).setNegativeButton("返回",(d,w)->returnToSources()));}
 void assignZip(String kind,File f){if(kind.equals("gba"))getPreferences(0).edit().putBoolean("gbaSkipped",false).apply();File previous=kind.equals("gba")?gba:kind.equals("main")?sources.mainZip:sources.androidZip;markChoice(kind,previous,f);if(kind.equals("gba"))gba=f;else if(kind.equals("main"))sources.mainZip=f;else if(kind.equals("android"))sources.androidZip=f;}
 void chooseZip(String kind){pendingKind=kind;getPreferences(0).edit().putString("pendingKind",kind).apply();String[] choices=kind.equals("gba")?new String[]{"不导入","浏览存储"}:new String[]{"浏览存储"};largeDialog(dialogBuilder().setCustomTitle(dialogTitle("选择 ZIP")).setView(choiceView(choices,(d,w)->{if(kind.equals("gba")&&w==0){markChoice("gba",gba,null);gba=null;getPreferences(0).edit().putBoolean("gbaSkipped",true).apply();invalidatePlan();save();render();return;}pick(false,f->{if(!f.getName().toLowerCase(Locale.ROOT).endsWith(".zip")){toast("请选择 ZIP 文件");return;}assignZip(kind,f);invalidatePlan();save();render();});})).setNegativeButton("返回",(d,w)->returnToSources()));}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request!=51||result!=RESULT_OK||data==null||data.getData()==null)return;
  pendingKind=getPreferences(0).getString("pendingKind","gba");
  Uri uri=data.getData();try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}
  String display="GBA整合包.zip";try(Cursor cursor=getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(cursor!=null&&cursor.moveToFirst())display=cursor.getString(0);}catch(Exception ignored){}
  if(display==null||!display.toLowerCase(Locale.ROOT).endsWith(".zip")){toast("请选择对应的 .zip 文件");return;}
  File direct=localDocument(uri);if(direct!=null&&direct.isFile()&&direct.canRead()){assignZip(pendingKind,direct);invalidatePlan();save();render();return;}
  final String name=display;task(()->{line("正在读取所选 ZIP 文件，请稍候…");File imports=getExternalFilesDir("imports");if(imports==null)imports=new File(getFilesDir(),"imports");SetupEngine.mkdir(imports);File target=new File(imports,System.currentTimeMillis()+"-"+name.replaceAll("[\\\\/:*?\"<>|\\r\\n]","_"));
   try(InputStream in=getContentResolver().openInputStream(uri);OutputStream out=new FileOutputStream(target)){if(in==null)throw new IOException("无法读取所选文件");SetupEngine.copy(in,out);}try(java.util.zip.ZipFile z=SetupEngine.openZip(target)){if(z.size()==0)throw new IOException("所选 ZIP 是空文件");}
   assignZip(pendingKind,target);invalidatePlan();save();line("✓ 已选择："+name);
  });
 }
 File localDocument(Uri uri){try{if("file".equals(uri.getScheme()))return new File(uri.getPath());if(DocumentsContract.isDocumentUri(this,uri)){String id=DocumentsContract.getDocumentId(uri);if(id.startsWith("raw:"))return new File(id.substring(4));if(uri.getAuthority().equals("com.android.externalstorage.documents")){int colon=id.indexOf(':');if(colon>=0){String volume=id.substring(0,colon);return new File(volume.equals("primary")?SetupEngine.HOME:"/storage/"+volume,id.substring(colon+1));}}}}catch(Exception ignored){}return null;}
 void pick(boolean folder,Chosen callback){
  if(!Environment.isExternalStorageManager()){storagePermission();return;}
  List<File> roots=new ArrayList<>();StorageManager sm=(StorageManager)getSystemService(STORAGE_SERVICE);
  for(StorageVolume v:sm.getStorageVolumes())if(v.getDirectory()!=null)roots.add(v.getDirectory());
  if(roots.isEmpty())roots.add(new File(SetupEngine.HOME));String[] labels=new String[roots.size()];for(int i=0;i<labels.length;i++)labels[i]=roots.get(i).getAbsolutePath();
  largeDialog(dialogBuilder().setCustomTitle(dialogTitle(folder?"选择文件夹":"选择 ZIP")).setView(choiceView(labels,(d,w)->browse(roots.get(w),roots.get(w),folder,callback,null))).setNegativeButton("返回",(d,w)->returnToSources()));
 }
 void markFreshInstall(){try{PackageInfo info=getPackageManager().getPackageInfo(getPackageName(),0);long stamp=info.lastUpdateTime,build=info.getLongVersionCode();android.content.SharedPreferences p=getPreferences(0);if(p.getLong("installStamp",-1)!=stamp||p.getLong("installBuild",-1)!=build)p.edit().putLong("installStamp",stamp).putLong("installBuild",build).putBoolean("cleanupPending",true).apply();}catch(Exception ignored){}}
 void cleanPreviousInstall(){if(!Environment.isExternalStorageManager()||!getPreferences(0).getBoolean("cleanupPending",false))return;File root=new File(SetupEngine.HOME);File[] files=root.listFiles();if(files!=null)for(File f:files)if(f.isFile()&&(f.getName().equals("KPA_Authorize.sh")||f.getName().startsWith("KPA_Setup_")&&f.getName().endsWith(".sh")))f.delete();getPreferences(0).edit().putBoolean("cleanupPending",false).apply();}
 void browse(File root,File dir,boolean folder,Chosen callback,File selected){
  File[] all=dir.listFiles(f->!f.getName().startsWith(".")&&(f.isDirectory()||!folder&&f.getName().toLowerCase(Locale.ROOT).endsWith(".zip")));
  if(all==null){toast("目录无权限或不可读取");return;}
  Arrays.sort(all,Comparator.<File,Boolean>comparing(f->!f.isDirectory()).thenComparing(File::getName));
  LinearLayout list=new LinearLayout(this);list.setOrientation(1);list.setPadding(dp(12),dp(8),dp(12),dp(8));
  if(folder)addBrowserRow(list,"当前文件夹",dir,true,dir.equals(selected),root,dir,folder,callback);
  if(!dir.equals(root))addBrowserRow(list,"↑ 返回上级",dir.getParentFile(),false,false,root,dir,folder,callback);
  for(File f:all)addBrowserRow(list,f.isDirectory()?"▸ "+f.getName():f.getName(),f,folder||!f.isDirectory(),f.equals(selected),root,dir,folder,callback);
  ScrollView scroll=new ScrollView(this);scroll.setVerticalScrollBarEnabled(false);scroll.setBackgroundColor(bg);scroll.addView(list);scroll.setTag(Integer.valueOf(Math.max(3,list.getChildCount())));
  AlertDialog.Builder builder=dialogBuilder().setCustomTitle(dialogTitle(dir.getAbsolutePath())).setView(scroll).setNegativeButton("返回",(d,w)->returnToSources());
  if(selected!=null)builder.setPositiveButton("确定",(d,w)->callback.accept(selected));
  largeDialog(builder);
 }
 void addBrowserRow(LinearLayout list,String label,File file,boolean selectable,boolean checked,File root,File dir,boolean folder,Chosen callback){
  LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(18),0,dp(12),0);row.setBackground(shape(checked?KpaTheme.RUNNING_SURFACE:panel));TextView name=text(label,KpaLayout.ITEM_TEXT,checked?runningColor:fg);name.setGravity(Gravity.CENTER_VERTICAL);name.setPadding(0,0,0,0);row.addView(name,new LinearLayout.LayoutParams(0,dp(50),1));
  if(selectable){RadioButton radio=new RadioButton(this);radio.setChecked(checked);radio.setButtonTintList(new android.content.res.ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{success,muted}));row.addView(radio,new LinearLayout.LayoutParams(dp(50),dp(50)));radio.setOnClickListener(v->replaceBrowse(v,()->browse(root,dir,folder,callback,file)));}
  LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(KpaLayout.BROWSER_ROW));lp.setMargins(0,dp(3),0,dp(3));list.addView(row,lp);focusable(row);row.setOnClickListener(v->{if(file.isDirectory()&&!label.equals("当前文件夹")&&!label.startsWith("↑"))replaceBrowse(v,()->browse(root,file,folder,callback,null));else if(label.startsWith("↑"))replaceBrowse(v,()->browse(root,file,folder,callback,null));else if(selectable)replaceBrowse(v,()->browse(root,dir,folder,callback,file));});
 }
 void replaceBrowse(View source,Runnable next){int y=0;View parent=source;while(parent!=null&&!(parent instanceof ScrollView)){android.view.ViewParent p=parent.getParent();parent=p instanceof View?(View)p:null;}if(parent instanceof ScrollView)y=((ScrollView)parent).getScrollY();final int restore=y;AlertDialog old=currentDialog;changeDialog(old,next);monitor.post(()->{AlertDialog now=currentDialog;if(now==null)return;View custom=now.getWindow().getDecorView().findViewWithTag("kpaDialog");ScrollView scroll=findScroll(custom);if(scroll!=null)scroll.scrollTo(0,restore);});}
 ScrollView findScroll(View view){if(view instanceof ScrollView)return (ScrollView)view;if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++){ScrollView found=findScroll(group.getChildAt(i));if(found!=null)return found;}}return null;}
 void scanApps(){
  List<File> archiveFiles=new ArrayList<>();SourceDiscovery.files(config,0,archiveFiles);File[] apks=archiveFiles.stream().filter(f->f.getName().toLowerCase(Locale.ROOT).endsWith(".apk")).toArray(File[]::new);
  for(AppSpec a:apps){a.apk=null;try{getPackageManager().getPackageInfo(a.pkg,0);a.installed=true;}catch(Exception e){a.installed=false;}}
  if(apks!=null){Arrays.sort(apks,Comparator.comparing(File::getName));for(File f:apks){PackageInfo pi=getPackageManager().getPackageArchiveInfo(f.getAbsolutePath(),0);if(pi!=null)for(AppSpec a:apps)if(a.pkg.equals(pi.packageName)){PackageInfo previous=a.apk==null?null:getPackageManager().getPackageArchiveInfo(a.apk.getAbsolutePath(),0);if(previous==null||pi.getLongVersionCode()>previous.getLongVersionCode())a.apk=f;}}}
  for(AppSpec a:apps){String manual=getPreferences(0).getString("apk."+a.pkg,"");if(!manual.isEmpty()){File f=new File(manual);PackageInfo info=f.isFile()?getPackageManager().getPackageArchiveInfo(f.getAbsolutePath(),0):null;if(info!=null&&a.pkg.equals(info.packageName))a.apk=f;}}
  for(AppSpec a:apps){a.configure=defaultConfigure(a);a.install=defaultInstall(a);}
 }
 void invalidatePlan(){getPreferences(0).edit().remove("executionError").putBoolean("executionConfirmed",false).apply();engine=null;run=null;discovered=false;selectionReport="";progress=0;preciseProgress=0;progressPhase="";currentWork="";}
 File setupScript(){if(run==null)return null;try{return new File(SetupEngine.read(new File(run,SetupEngine.SCRIPT_PATH)).trim());}catch(Exception e){return null;}}
 void showRootInstructions(String key){
  File file=key.equals("setup")?setupScript():key.equals("check")&&run!=null?new File(SetupEngine.HOME,"KPA_Check_"+run.getName().replace('-','_')+".sh"):new File(SetupEngine.HOME,key);
  if(file==null||!file.isFile()){dialogBuilder().setTitle("存储 Root 执行说明").setMessage("接口检测通过，只表示可调用；不会自动执行初始化。\n\n第二页检测通过后进入第三页，二次确认后执行。完成后会生成系统存储根目录的 KPA_Setup_*.sh。\n\n在初始化页面点击“打开掌机管理”，进入设备 → Root 脚本，选择本次脚本并运行。运行后返回助手读取结果。\n\n纯净底稿是首次打开应用生成的文件，不能用定制包或覆盖前备份代替。").setPositiveButton("知道了",null).show();return;}
  showScript(file,key.equals("check")?"读取文件完整性与存储授权状态，不修改配置。":"安装 APK、导入纯净初始化文件、执行定制配置覆盖。不创建备份。接口检测通过不代表本脚本已执行。");
 }
 void showScript(File f,String purpose){
  if(f==null||!f.isFile()){toast("请先生成脚本");return;}
  dialogBuilder().setTitle("执行存储 Root 脚本").setMessage(purpose+"\n\n掌机管理 → 设备 → Root 脚本 → 选择系统存储根目录的下列文件 → 运行。\n\n"+f.getAbsolutePath()+"\n\n完成后返回 KPA助手读取结果。").setNeutralButton("复制路径",(d,w)->copyPath(f)).setPositiveButton("掌机管理",(d,w)->openRootPage()).setNegativeButton("返回助手",null).show();
 }
 void copyPath(File f){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Storage Root script",f.getAbsolutePath()));toast("路径已复制");}
 void auditConfigs(boolean preview)throws Exception {Map<String,String> report=ConfigAudit.inspect(this,config,apps);initialStates.clear();initialStates.putAll(report);for(AppSpec app:apps)if(report.containsKey(app.pkg))recordCheck(app.label+"："+report.get(app.pkg),preview);}

 boolean scriptDone(){try{return run!=null&&SetupEngine.read(new File(run,SetupEngine.STATUS)).trim().equals("DONE");}catch(Exception e){return false;}}
 boolean permissionPassed(String pkg){return verifiedPermissions.containsKey(pkg)?Boolean.TRUE.equals(verifiedPermissions.get(pkg)):getPreferences(0).getBoolean(pkg+".verifiedPermission",false);}
 void collectPermissions(RootBridge rb)throws Exception {int yes=0,total=0;for(AppSpec a:apps)if(a.configure){total++;boolean passed=true;try{PackageInfo pi=getPackageManager().getPackageInfo(a.pkg,PackageManager.GET_PERMISSIONS);if(pi.requestedPermissions!=null)for(int i=0;i<pi.requestedPermissions.length;i++){String p=pi.requestedPermissions[i];if(p.equals("android.permission.MANAGE_EXTERNAL_STORAGE")){if(rb==null||!rb.call("cmd appops get "+RootBridge.q(a.pkg)+" MANAGE_EXTERNAL_STORAGE").contains("allow"))passed=false;}else if(p.equals("android.permission.READ_EXTERNAL_STORAGE")||p.equals("android.permission.WRITE_EXTERNAL_STORAGE")){if((pi.requestedPermissionsFlags[i]&PackageInfo.REQUESTED_PERMISSION_GRANTED)==0)passed=false;}}}catch(Exception e){passed=false;}verifiedPermissions.put(a.pkg,passed);getPreferences(0).edit().putBoolean(a.pkg+".verifiedPermission",passed).apply();if(passed)yes++;}final int y=yes,t=total;runOnUiThread(()->summaryReport="系统存储权限："+y+" / "+t+" 款已通过。应用内目录、BIOS与手柄请按设置教程确认。");}
 void readRootResult()throws Exception {
  if(run==null)throw new Exception("请先一键检测，生成本批次脚本");File state=new File(run,SetupEngine.STATUS);if(!state.isFile()){line("初始化尚未执行。请执行初始化，或在掌机管理 → 设备 → Root脚本运行本批次脚本。");return;}
  String s=SetupEngine.read(state).trim();if(s.equals("DONE")){if(!initialPassed())throw new Exception("本批次缺少完整的文件存在核验记录，请重新准备");finishBatch();finalized=true;runOnUiThread(()->{updateProgress(100);save();});}
  else if(s.equals("ERROR"))throw new Exception("初始化中断，请查看本批次执行日志.txt；不会创建备份");else line("当前阶段："+s+"。脚本仍在执行，请稍后再检测。");
 }
 void finishBatch()throws Exception {RootBridge rb=null;try{rb=new RootBridge(this);rb.check();}catch(Exception ignored){rb=null;}collectPermissions(rb);new File(SetupEngine.HOME,"KPA_Authorize.sh").delete();line("✓ 初次安装与覆盖已核验，请在最后一页查看手动设置教程。");}
 void launch(String pkg){try{Intent i=getPackageManager().getLaunchIntentForPackage(pkg);if(i==null){toast("应用未安装或没有启动入口");return;}startActivity(i);}catch(Exception e){toast(e.getMessage());}}
 void verify()throws Exception {
  if(run==null||!scriptDone())throw new Exception("请先完成本批次初始化脚本");RootBridge rb=null;try{rb=new RootBridge(this);rb.check();}catch(Exception ignored){rb=null;}
  if(rb==null){File entry=IntegrityVerifier.exportEntry(run);line("本次复核需通过掌机助手的 Root脚本入口执行："+entry);runOnUiThread(()->showScript(entry,"检查所有目标文件是否存在。不会启动应用或修改配置。"));return;}
  rb.call("sh "+RootBridge.q(new File(run,SetupEngine.VERIFY_SCRIPT).getAbsolutePath()));collectPermissions(rb);
  if(IntegrityVerifier.passed(run)){finishBatch();line("✓ 本次文件存在复核通过："+IntegrityVerifier.count(run)+" 个目标文件。");}
  else{String details=new File(run,SetupEngine.DETAILS).isFile()?SetupEngine.read(new File(run,SetupEngine.DETAILS)):"无详细记录";StringBuilder errors=new StringBuilder();int n=0;for(String l:details.split("\n"))if(!l.endsWith(": OK")&&n++<30)errors.append(l).append('\n');line("本次文件存在复核未通过。初次覆盖通过记录仍保留。\n"+errors);runOnUiThread(()->summaryReport="本次复核发现文件或目录异常，请查看操作记录。初次覆盖通过记录保留。");}
 }
 static boolean needsDirectory(String p){return p.equals("com.dsemu.drastic")||p.equals("xyz.aethersx2.android")||p.equals("org.pegasus_frontend.android")||p.equals("org.dolphinemu.mmjr")||p.equals("org.citra.emu");}
 static String requirements(String p){
  if(p.equals("org.pegasus_frontend.android"))return "允许存储 / 所有文件访问。重新加载媒体缓存；使用 NDS 等模拟器时，在“可访问的安卓目录”添加对应游戏文件夹。";
  if(p.equals("com.retroarch.aarch64"))return "允许存储 / 所有文件访问。核心、界面资源和初始化版本已提前导入，不需要再等待首次解包；手柄模式仍应在系统中设置为 Xbox、日式 ABXY。";
  if(p.equals("com.dsemu.drastic"))return "选择外置数据目录：内存/DraStic，确认“使用此文件夹”。按游戏需要授予麦克风权限。";
  if(p.equals("xyz.aethersx2.android"))return "若出现首次引导，按默认选项完成。添加实际 PS2 游戏目录；确认 BIOS 和控制器映射。已有公开配置导入不等于系统目录授权已完成。";
  if(p.equals("org.dolphinemu.mmjr"))return "允许存储权限；若提示选择数据目录，使用内存/mmjr2-vbi，并添加游戏目录。";
  if(p.equals("org.citra.emu"))return "允许存储权限；如需目录授权，选择内存/citra-emu 和实际 3DS 游戏目录。";
  return "允许应用申请的存储权限，确认游戏目录可读取。";
 }
 void save(){android.content.SharedPreferences.Editor e=getPreferences(0).edit().putString("config",config==null?"":config.getAbsolutePath()).putString("gba",gba==null?"":gba.getAbsolutePath()).putString("destination",destination.getAbsolutePath()).putInt("step",step).putInt("progress",progress).putString("mainZip",sources.mainZip==null?"":sources.mainZip.getAbsolutePath()).putString("androidZip",sources.androidZip==null?"":sources.androidZip.getAbsolutePath()).putString("lists",sources.lists==null?"":sources.lists.getAbsolutePath()).putBoolean("grantStorage",sources.grantStorage).putString("run",run==null?"":run.getAbsolutePath());for(AppSpec a:apps)e.putBoolean(a.pkg+".install",a.install).putBoolean(a.pkg+".configure",a.configure).putBoolean(a.pkg+".directory",Boolean.TRUE.equals(manualDirectory.get(a.pkg)));e.apply();}
 void restore(){android.content.SharedPreferences p=getPreferences(0);String cfg=p.getString("config",""),g=p.getString("gba",""),r=p.getString("run","");if(!cfg.isEmpty())config=new File(cfg);if(!g.isEmpty()&&!p.getBoolean("gbaSkipped",false))gba=new File(g);destination=new File(p.getString("destination",SetupEngine.HOME));if(!r.isEmpty())run=new File(r);if(run!=null&&!new File(run,SetupEngine.SCRIPT_PATH).isFile()&&!new File(run,SetupEngine.STATUS).isFile()){run=null;p.edit().putString("resumeRun",r).putString("run", "").putString("executionError","准备过程已中断，请重新确认执行").apply();}scanApps();for(AppSpec a:apps){a.install=p.getBoolean(a.pkg+".install",a.install);a.configure=p.getBoolean(a.pkg+".configure",a.configure);manualDirectory.put(a.pkg,p.getBoolean(a.pkg+".directory",false));}sources.discover(config==null?new File("/invalid"):config);sources.mainZip=storedFile(p,"mainZip",sources.mainZip);sources.androidZip=storedFile(p,"androidZip",sources.androidZip);sources.lists=storedFile(p,"lists",sources.lists);sources.grantStorage=p.getBoolean("grantStorage",true);progress=p.getInt("progress",0);step=Math.max(0,Math.min(p.getInt("step",0),3));}

 File storedFile(android.content.SharedPreferences p,String key,File fallback){if(!p.contains(key))return fallback;String path=p.getString(key,"");return path.isEmpty()?null:new File(path);}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 @Override public void onBackPressed(){if(interactionLocked()){toast("正在初始化，请等待当前步骤完成");return;}if(step>0){int target=step-1;if(target==2&&!selectionReport.startsWith("✓")&&run==null)target=1;if(!Environment.isExternalStorageManager()||!authorizationPassed())target=0;switchStep(target-step);}else super.onBackPressed();}
 @Override protected void onResume(){super.onResume();if(rootGuideActive)stopRootPageGuide();monitor.removeCallbacksAndMessages(null);if(!interactionLocked())clearExecutionProtection();if(!Environment.isExternalStorageManager()){if(!permissionPrompted){permissionPrompted=true;storagePermission();}}else{permissionPrompted=false;cleanPreviousInstall();generateAuthorization();}if(step==2&&executionRunning()&&!scriptDone()){getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);render();monitorRunningOverlay();return;}if(content!=null&&!busy){if(step==2&&scriptDone()&&initialPassed()&&!finalized){finalized=true;progress=100;task(this::finishBatch);}else render();}if(step==1)autoDiscover();autoRootCheck(false);if(step==0)monitorAuthorization();else if(step==2)monitorExecution();}
 @Override public void onWindowFocusChanged(boolean hasFocus){super.onWindowFocusChanged(hasFocus);if(!hasFocus)releaseControllerFocus();}
 @Override protected void onUserLeaveHint(){releaseControllerFocus();super.onUserLeaveHint();}
 @Override protected void onPause(){releaseControllerFocus();if(!interactionLocked()){getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);monitor.removeCallbacksAndMessages(null);}super.onPause();}
 @Override protected void onDestroy(){monitor.removeCallbacksAndMessages(null);stopRootPageGuide();clearExecutionProtection();getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);super.onDestroy();}

}
