package cn.pegasus.setup;
import java.io.*;import java.util.*;import java.util.zip.*;
/** 按内容识别资料，文件名只作辅助。 */
final class SourceDiscovery {
 static final String[] PACKAGES={"org.pegasus_frontend.android","com.retroarch.aarch64","com.dsemu.drastic","org.ppsspp.ppsspp","xyz.aethersx2.android","org.citra.emu","org.mupen64plusae.v3.fzurita.pro","org.dolphinemu.mmjr"};
 static final Map<String,Integer> KIND_CACHE=Collections.synchronizedMap(new LinkedHashMap<String,Integer>(){protected boolean removeEldestEntry(Map.Entry<String,Integer> e){return size()>128;}});
 static String fileKey(File file){return file.getAbsolutePath()+"|"+file.length()+"|"+file.lastModified();}
 static void files(File dir,int depth,List<File> out){if(dir==null||depth>5||!dir.isDirectory()||dir.getName().equals("Android")||dir.getName().equals("KPA-Tools")||dir.getName().equals("PegasusG-Setup"))return;File[] fs=dir.listFiles();if(fs==null)return;for(File f:fs){if(f.isDirectory()&&!f.getName().startsWith("."))files(f,depth+1,out);else if(f.isFile()){String n=f.getName().toLowerCase(Locale.ROOT);if(n.endsWith(".zip")||n.endsWith(".apk"))out.add(f);}}}
 static String path(String raw){String n=("/"+raw.replace('\\','/')).toLowerCase(Locale.ROOT);while(n.contains("//"))n=n.replace("//","/");return n;}
 static boolean packagePath(String n){for(String pkg:PACKAGES)if(n.contains("/android/data/"+pkg.toLowerCase(Locale.ROOT)+"/"))return true;return false;}
 static int kind(File file){String key=fileKey(file);Integer cached=KIND_CACHE.get(key);if(cached!=null)return cached;boolean pg=false,ra=false,gba=false,android=false;try(ZipFile zip=SetupEngine.openZip(file)){Enumeration<? extends ZipEntry> entries=zip.entries();while(entries.hasMoreElements()){ZipEntry e=entries.nextElement();if(e.isDirectory())continue;String n=path(e.getName());pg|=n.contains("/pegasus-frontend/")&&(n.endsWith("settings.txt")||n.endsWith("game_dirs.txt")||n.endsWith("metadata.pegasus.txt"))||n.contains("/pg/")&&n.endsWith("metadata.pegasus.txt");ra|=n.contains("/retroarch/")&&(n.endsWith("retroarch.cfg")||n.contains("/config/")||n.contains("/overlays/")||n.contains("/shaders/"));gba|=n.contains("/roms/gba/")&&(n.endsWith("metadata.pegasus.txt")||n.matches(".*\\.(gba|zip|7z)$"));android|=packagePath(n);if(gba||android||pg&&ra)break;}}catch(Exception ignored){KIND_CACHE.put(key,0);return 0;}int result=pg&&ra?1:gba?2:android?3:0;KIND_CACHE.put(key,result);return result;}
 static List<File> matching(File root,int kind){List<File> all=new ArrayList<>(),found=new ArrayList<>();files(root,0,all);for(File f:all)if(f.getName().toLowerCase(Locale.ROOT).endsWith(".zip")&&kind(f)==kind)found.add(f);return found;}
 static File unique(File root,int kind)throws IOException{List<File> found=matching(root,kind);if(found.size()!=1)throw new IOException(found.isEmpty()?"未找到内容匹配的资料，请选择补全":"发现多个内容匹配的资料，请手动确认");return found.get(0);}
 static int bundleScore(File dir){List<File> all=new ArrayList<>();files(dir,0,all);int apks=0,main=0,android=0;for(File f:all){String n=f.getName().toLowerCase(Locale.ROOT);if(n.endsWith(".apk"))apks++;else if(n.endsWith(".zip")){int k=kind(f);if(k==1)main++;if(k==3)android++;}}return main*40+android*30+Math.min(apks,12)*3+(findLists(dir)!=null?20:0);}
 static boolean storageRoot(File dir){String path=dir.getAbsolutePath();return path.equals(SetupEngine.HOME)||path.matches("/storage/[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}");}
 static File bundleRoot(File zip){File best=zip.getParentFile(),p=best;int score=bundleScore(best);for(int level=0;level<3;level++){p=p==null?null:p.getParentFile();if(p==null||!p.isDirectory()||storageRoot(p)||p.getAbsolutePath().equals("/storage"))break;int current=bundleScore(p);if(current>score){score=current;best=p;}}return best;}
 static int metadataCount(File dir,int depth){if(dir==null||depth>2||!dir.isDirectory())return 0;File[] fs=dir.listFiles();if(fs==null)return 0;int count=0;for(File f:fs){if(f.isDirectory())count+=metadataCount(f,depth+1);else if(f.getName().equalsIgnoreCase("metadata.pegasus.txt"))count++;}return count;}
 static File findLists(File root){if(root==null||!root.isDirectory())return null;File best=null;int bestCount=0;ArrayDeque<File> dirs=new ArrayDeque<>();ArrayDeque<Integer> depths=new ArrayDeque<>();dirs.add(root);depths.add(0);while(!dirs.isEmpty()){File dir=dirs.remove();int depth=depths.remove();File[] fs=dir.listFiles();if(fs==null)continue;int collections=0;for(File f:fs)if(f.isDirectory()){if(metadataCount(f,1)>0)collections++;if(depth<5&&!f.getName().equals("Android")){dirs.add(f);depths.add(depth+1);}}if(collections>bestCount){best=dir;bestCount=collections;}}return best;}
}
